# Generated by Django 5.0.1 on 2024-03-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siren_web",
            "0002_sirensystem_remove_generatorattributes_capacity_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storageattributes",
            name="capacity_max",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="capacity_min",
        ),
        migrations.AddField(
            model_name="technologies",
            name="capacity_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technologies",
            name="capacity_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
