# Generated by Django 5.0.1 on 2024-03-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0003_remove_storageattributes_capacity_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageattributes",
            name="min_runtime",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="warm_time",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
