# Generated by Django 5.0.1 on 2024-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0004_storageattributes_min_runtime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatorattributes",
            name="initial",
        ),
        migrations.AddField(
            model_name="technologies",
            name="initial",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
