# Generated by Django 5.0.1 on 2024-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0005_remove_generatorattributes_initial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatorattributes",
            name="fuel",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
