# Generated by Django 5.0.1 on 2024-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0006_alter_generatorattributes_fuel"),
    ]

    operations = [
        migrations.AddField(
            model_name="technologies",
            name="lcoe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="technologies",
            name="lcoe_cf",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
