# Generated by Django 5.0.1 on 2024-03-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0009_alter_demand_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Constraints",
        ),
    ]
