# Generated by Django 5.0.1 on 2024-03-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0010_delete_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="demand",
            unique_together=set(),
        ),
    ]
