# Generated by Django 5.0.1 on 2024-03-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0017_scenariosfacilities_merit_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="variations",
            name="dimension",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="variations",
            name="idtechnologies",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="siren_web.technologies",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variations",
            name="iterations",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variations",
            name="startval",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="variations",
            name="step",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
