# Generated by Django 5.0.1 on 2024-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0019_remove_variations_dimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variations",
            name="dimension",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
