# Generated by Django 5.0.1 on 2024-03-14 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0023_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variations",
            name="idtechnologies",
            field=models.ForeignKey(
                db_column="idtechnologies",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="siren_web.technologies",
            ),
        ),
    ]
