# Generated by Django 5.0.1 on 2024-03-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0024_alter_variations_idtechnologies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variations",
            name="idtechnologies",
        ),
    ]
