# Generated by Django 5.0.1 on 2024-03-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0025_remove_variations_idtechnologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="variations",
            name="idtechnologies",
            field=models.ForeignKey(
                db_column="idTechnologies",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="siren_web.technologies",
            ),
            preserve_default=False,
        ),
    ]
