# Generated by Django 5.0.1 on 2024-03-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0026_variations_idtechnologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="technologies",
            name="technology_signature",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
