# Generated by Django 5.0.1 on 2024-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0027_technologies_technology_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technologies",
            name="technology_name",
            field=models.CharField(default=" ", max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="technologies",
            name="technology_signature",
            field=models.CharField(default=" ", max_length=20),
            preserve_default=False,
        ),
    ]
