# Generated by Django 5.0.1 on 2024-03-19 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0028_alter_technologies_technology_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenariosTechnologies",
            fields=[
                (
                    "idscenariostechnologies",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("merit_order", models.IntegerField(blank=True, null=True)),
                (
                    "idscenarios",
                    models.ForeignKey(
                        db_column="idScenarios",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="siren_web.scenarios",
                    ),
                ),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        db_column="idTechnologies",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="siren_web.technologies",
                    ),
                ),
            ],
            options={
                "db_table": "ScenariosTechnologies",
            },
        ),
    ]
