# Generated by Django 5.0.1 on 2024-03-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0029_scenariostechnologies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScenariosTechnologies",
        ),
    ]
