# Generated by Django 5.0.1 on 2024-03-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0030_delete_scenariostechnologies"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenariosTechnologies",
            fields=[
                (
                    "idscenariostechnologies",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("merit_order", models.IntegerField(null=True)),
                (
                    "idscenarios",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siren_web.scenarios",
                    ),
                ),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siren_web.technologies",
                    ),
                ),
            ],
            options={
                "db_table": "ScenariosTechnologies",
            },
        ),
        migrations.AddField(
            model_name="technologies",
            name="scenarios",
            field=models.ManyToManyField(
                blank=True,
                through="siren_web.ScenariosTechnologies",
                to="siren_web.scenarios",
            ),
        ),
    ]
