# Generated by Django 5.0.1 on 2024-03-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0033_remove_scenariosfacilities_merit_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageattributes",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
