# Generated by Django 5.0.1 on 2024-03-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0035_rename_context_settings_sw_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenariosSettings",
            fields=[
                (
                    "idscenariossettings",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("sw_context", models.CharField(blank=True, max_length=20, null=True)),
                ("parameter", models.CharField(blank=True, max_length=45, null=True)),
                ("value", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "idscenarios",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="siren_web.scenarios",
                    ),
                ),
            ],
            options={
                "db_table": "ScenariosSettings",
            },
        ),
    ]
