# Generated by Django 5.0.1 on 2024-03-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0037_scenariossettings_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="iddemand",
            field=models.AutoField(
                db_column="idDemand", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="idfacilities",
            field=models.AutoField(
                db_column="idfacilities", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="idgenetics",
            field=models.AutoField(
                db_column="idGenetics", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="optimisation",
            name="idoptimisation",
            field=models.AutoField(
                db_column="idOptimisation", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="scenariossettings",
            name="idscenariossettings",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="settings",
            name="idsettings",
            field=models.AutoField(
                db_column="idSettings", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="zones",
            name="idzones",
            field=models.AutoField(
                db_column="idZones", primary_key=True, serialize=False
            ),
        ),
    ]
