# Generated by Django 5.0.1 on 2024-03-25 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siren_web",
            "0038_alter_demand_iddemand_alter_facilities_idfacilities_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariossettings",
            name="idscenarios",
            field=models.ForeignKey(
                db_column="idscenarios",
                on_delete=django.db.models.deletion.RESTRICT,
                to="siren_web.scenarios",
            ),
        ),
    ]
