# Generated by Django 5.0.1 on 2024-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0040_alter_scenariossettings_idscenarios_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="iddemand",
            field=models.PositiveIntegerField(
                db_column="idDemand", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="idfacilities",
            field=models.PositiveIntegerField(
                db_column="idfacilities", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="idgenetics",
            field=models.PositiveIntegerField(
                db_column="idGenetics", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="optimisation",
            name="idoptimisation",
            field=models.PositiveIntegerField(
                db_column="idOptimisation", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="idsettings",
            field=models.PositiveIntegerField(
                db_column="idSettings", primary_key=True, serialize=False
            ),
        ),
    ]
