# Generated by Django 5.0.1 on 2024-03-28 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siren_web",
            "0042_alter_demand_iddemand_alter_facilities_idfacilities_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="idvariations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="siren_web.variations",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="idscenarios",
            field=models.ForeignKey(
                blank=True,
                db_column="idScenarios",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="siren_web.scenarios",
            ),
        ),
    ]
