# Generated by Django 5.0.1 on 2024-03-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0044_alter_analysis_idvariations"),
    ]

    operations = [
        migrations.AddField(
            model_name="variations",
            name="idscenarios",
            field=models.ForeignKey(
                blank=True,
                db_column="idScenarios",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="siren_web.scenarios",
            ),
        ),
        migrations.AlterField(
            model_name="variations",
            name="idtechnologies",
            field=models.ForeignKey(
                db_column="idTechnologies",
                on_delete=django.db.models.deletion.RESTRICT,
                to="siren_web.technologies",
            ),
        ),
    ]
