# Generated by Django 5.0.1 on 2024-03-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0045_variations_idscenarios_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variations",
            name="idscenarios",
            field=models.ForeignKey(
                blank=True,
                db_column="idScenarios",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="siren_web.scenarios",
            ),
        ),
    ]
