# Generated by Django 5.0.1 on 2024-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0046_alter_variations_idscenarios"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="basis",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="idvariations",
        ),
        migrations.AddField(
            model_name="analysis",
            name="variation",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
