# Generated by Django 5.0.1 on 2024-03-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siren_web",
            "0047_remove_analysis_basis_remove_analysis_idvariations_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
