# Generated by Django 5.0.1 on 2024-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0049_alter_demand_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technologies",
            name="capacity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="capacity_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="capacity_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
    ]
