# Generated by Django 5.0.1 on 2024-04-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0051_supplyfactors_col_supplyfactors_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatorattributes",
            name="idtechnologies",
            field=models.ForeignKey(
                db_column="idTechnologies",
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.technologies",
            ),
        ),
        migrations.AlterField(
            model_name="storageattributes",
            name="idtechnologies",
            field=models.ForeignKey(
                blank=True,
                db_column="idTechnologies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.technologies",
            ),
        ),
    ]
