# Generated by Django 5.0.1 on 2024-04-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0052_alter_generatorattributes_idtechnologies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatorattributes",
            name="generated",
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name="technologies",
            name="capacity_factor",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
