# Generated by Django 5.0.1 on 2024-04-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0053_generatorattributes_generated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyfactors",
            name="quantum",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="capacity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="capacity_max",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="capacity_min",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="emissions",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="initial",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="lcoe",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="lcoe_cf",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="mult",
            field=models.FloatField(null=True),
        ),
    ]
