# Generated by Django 5.0.1 on 2024-04-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0054_alter_supplyfactors_quantum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="capacity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="capacityfactor",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="generation",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="transmitted",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="generatorattributes",
            name="fuel",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="generatorattributes",
            name="generated",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="better",
            field=models.FloatField(db_column="Better", null=True),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="maxvalue",
            field=models.FloatField(db_column="MaxValue", null=True),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="minvalue",
            field=models.FloatField(db_column="MinValue", null=True),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="step",
            field=models.FloatField(db_column="Step", null=True),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="weight",
            field=models.FloatField(db_column="Weight", null=True),
        ),
        migrations.AlterField(
            model_name="genetics",
            name="worse",
            field=models.FloatField(db_column="Worse", null=True),
        ),
        migrations.AlterField(
            model_name="optimisation",
            name="capacity",
            field=models.FloatField(db_column="Capacity", null=True),
        ),
        migrations.AlterField(
            model_name="optimisation",
            name="capacitymax",
            field=models.FloatField(db_column="CapacityMax", null=True),
        ),
        migrations.AlterField(
            model_name="optimisation",
            name="capacitymin",
            field=models.FloatField(db_column="CapacityMin", null=True),
        ),
        migrations.AlterField(
            model_name="optimisation",
            name="capacitystep",
            field=models.FloatField(db_column="CapacityStep", null=True),
        ),
        migrations.AlterField(
            model_name="storageattributes",
            name="discharge_max",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="storageattributes",
            name="min_runtime",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="storageattributes",
            name="recharge_max",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="storageattributes",
            name="warm_time",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="capacity_factor",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="capex",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="discount_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="fom",
            field=models.FloatField(db_column="FOM", null=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="vom",
            field=models.FloatField(db_column="VOM", null=True),
        ),
        migrations.AlterField(
            model_name="variations",
            name="endval",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="variations",
            name="startval",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="variations",
            name="step",
            field=models.FloatField(null=True),
        ),
    ]
