# Generated by Django 5.0.1 on 2024-04-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0055_alter_facilities_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technologies",
            name="lifetime",
            field=models.FloatField(null=True),
        ),
    ]
