# Generated by Django 5.0.1 on 2024-04-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0056_alter_technologies_lifetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatorattributes",
            name="area",
            field=models.FloatField(null=True),
        ),
    ]
