# Generated by Django 5.0.1 on 2024-04-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0057_generatorattributes_area"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variations",
            old_name="iterations",
            new_name="stages",
        ),
    ]
