# Generated by Django 5.0.1 on 2024-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0059_alter_analysis_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="stage",
            field=models.IntegerField(null=True),
        ),
    ]
