# Generated by Django 5.0.1 on 2024-04-26 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0060_alter_analysis_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimisation",
            name="idscenarios",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="optimisation",
            name="idtechnologies",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="variations",
            name="idscenarios",
            field=models.ForeignKey(
                db_column="idScenarios",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.scenarios",
            ),
        ),
    ]
