# Generated by Django 5.0.1 on 2024-04-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siren_web", "0062_alter_optimisation_idscenarios_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Optimisation",
            new_name="Optimisations",
        ),
        migrations.AlterModelTable(
            name="optimisations",
            table="Optimisations",
        ),
    ]
