# Generated by Django 5.0.1 on 2024-10-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0065_technologies_capacities"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="facility_code",
            field=models.CharField(
                blank=True, db_column="facility_code", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="facilities",
            name="no_turbines",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="tilt",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="turbine",
            field=models.CharField(
                blank=True, db_column="turbine", max_length=45, null=True
            ),
        ),
    ]
