# Generated by Django 5.0.1 on 2024-10-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0066_facilities_facility_code_facilities_no_turbines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="direction",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="grid_line",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="hub_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="participant_code",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="power_file",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="storage_hours",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
