# Generated by Django 5.0.1 on 2024-10-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0067_facilities_area_facilities_direction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="area",
        ),
        migrations.AddField(
            model_name="technologies",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
