# Generated by Django 5.0.1 on 2024-10-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0068_remove_facilities_area_technologies_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariossettings",
            name="value",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
