# Generated by Django 5.0.1 on 2024-10-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0069_alter_scenariossettings_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
