# Generated by Django 5.0.1 on 2024-10-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0070_alter_settings_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_interval", models.DateTimeField()),
                ("reference_price", models.FloatField()),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
