# Generated by Django 5.0.1 on 2024-10-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0073_alter_tradingprice_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="registered_from",
            field=models.DateField(null=True),
        ),
    ]
