# Generated by Django 5.0.1 on 2024-10-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0074_facilities_registered_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="active",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
