# Generated by Django 5.0.1 on 2024-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0075_facilities_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingprice",
            name="trading_month",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="tradingprice",
            name="trading_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
