# Generated by Django 5.0.1 on 2024-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0076_tradingprice_trading_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingprice",
            name="trading_month",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
