# Generated by Django 5.0.1 on 2024-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0077_alter_tradingprice_trading_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="turbine",
            field=models.CharField(
                blank=True, db_column="turbine", max_length=70, null=True
            ),
        ),
    ]
