# Generated by Django 5.0.1 on 2024-11-13 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0078_alter_facilities_turbine"),
    ]

    operations = [
        migrations.CreateModel(
            name="capacities",
            fields=[
                (
                    "idcapacities",
                    models.AutoField(
                        db_column="idsupplyfactors", primary_key=True, serialize=False
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("hour", models.IntegerField(blank=True, null=True)),
                ("quantum", models.FloatField(null=True)),
                (
                    "idfacilities",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfacilities",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="siren_web.facilities",
                    ),
                ),
            ],
            options={
                "db_table": "capacities",
            },
        ),
    ]
