# Generated by Django 5.0.1 on 2024-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0079_capacities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capacities",
            name="idcapacities",
            field=models.AutoField(
                db_column="idcapacities", primary_key=True, serialize=False
            ),
        ),
    ]
