# Generated by Django 5.0.1 on 2025-05-16 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0081_technologyyears"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatorattributes",
            name="year",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="year",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="capex",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="fom",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="vom",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="year",
        ),
    ]
