# Generated by Django 5.0.1 on 2025-05-16 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0082_remove_generatorattributes_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technologies",
            name="approach",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="capacities",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="capacity_factor",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="capacity_max",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="capacity_min",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="capacity_step",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="emissions",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="initial",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="lcoe",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="lcoe_cf",
        ),
        migrations.RemoveField(
            model_name="technologies",
            name="mult",
        ),
    ]
