# Generated by Django 5.0.1 on 2025-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0083_remove_technologies_approach_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatorattributes",
            name="fuel",
        ),
        migrations.RemoveField(
            model_name="generatorattributes",
            name="generated",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="min_runtime",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="rampdown_max",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="rampup_max",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="warm_time",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="approach",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="capacities",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="capacity_factor",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="capacity_max",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="capacity_min",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="capacity_step",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="discount_rate",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="emissions",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="initial",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="lcoe",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="lcoe_cf",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="lifetime",
        ),
        migrations.RemoveField(
            model_name="technologyyears",
            name="mult",
        ),
        migrations.AddField(
            model_name="generatorattributes",
            name="capacity_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="generatorattributes",
            name="capacity_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="generatorattributes",
            name="rampdown_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatorattributes",
            name="rampup_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technologies",
            name="emissions",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="technologyyears",
            name="fuel",
            field=models.FloatField(null=True),
        ),
    ]
