# Generated by Django 5.0.1 on 2025-05-18 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0084_remove_generatorattributes_fuel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatorattributes",
            name="area",
        ),
    ]
