# Generated by Django 5.0.1 on 2025-05-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0085_remove_generatorattributes_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="facility_code",
            field=models.CharField(
                blank=True, db_column="facility_code", max_length=30, null=True
            ),
        ),
    ]
