# Generated by Django 5.0.1 on 2025-05-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0086_alter_facilities_facility_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="idscenarios",
            field=models.ForeignKey(
                db_column="idScenarios",
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.scenarios",
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="idtechnologies",
            field=models.ForeignKey(
                db_column="idTechnologies",
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.technologies",
            ),
        ),
    ]
