# Generated by Django 5.0.1 on 2025-05-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0087_alter_demand_idscenarios_alter_demand_idtechnologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="existing",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="idscenarios",
            field=models.ForeignKey(
                blank=True,
                db_column="idScenarios",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.scenarios",
            ),
        ),
        migrations.AlterField(
            model_name="scenariosfacilities",
            name="idfacilities",
            field=models.ForeignKey(
                db_column="idfacilities",
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.facilities",
            ),
        ),
        migrations.AlterField(
            model_name="scenariosfacilities",
            name="idscenarios",
            field=models.ForeignKey(
                db_column="idScenarios",
                on_delete=django.db.models.deletion.CASCADE,
                to="siren_web.scenarios",
            ),
        ),
        migrations.AlterField(
            model_name="scenariossettings",
            name="idscenarios",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="siren_web.scenarios"
            ),
        ),
        migrations.AlterField(
            model_name="supplyfactors",
            name="idscenarios",
            field=models.ForeignKey(
                db_column="idscenarios",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="siren_web.scenarios",
            ),
        ),
    ]
