# Generated by Django 5.0.1 on 2025-05-23 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0088_alter_analysis_idscenarios_and_more"),
        ("siren_web", "0088_facilities_existing_alter_analysis_idscenarios_and_more"),
    ]

    operations = []
