# Generated by Django 5.0.1 on 2025-05-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0089_merge_20250523_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="facility_code",
            field=models.CharField(
                blank=True,
                db_column="facility_code",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="facility_name",
            field=models.CharField(
                blank=True,
                db_column="facility_name",
                max_length=45,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="scenarios",
            name="title",
            field=models.CharField(
                blank=True, db_column="Title", max_length=45, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="technology_name",
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name="technologies",
            name="technology_signature",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="zones",
            name="name",
            field=models.CharField(
                blank=True,
                db_collation="utf8mb4_0900_ai_ci",
                max_length=45,
                null=True,
                unique=True,
            ),
        ),
    ]
