# Generated by Django 5.0.1 on 2025-06-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0091_remove_supplyfactors_idscenarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariostechnologies",
            name="capacity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="scenariostechnologies",
            name="idscenarios",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="siren_web.scenarios"
            ),
        ),
        migrations.AlterField(
            model_name="scenariostechnologies",
            name="idtechnologies",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="siren_web.technologies"
            ),
        ),
    ]
