# Generated by Django 5.0.1 on 2025-06-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0092_scenariostechnologies_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplyfactors",
            name="col",
        ),
        migrations.AddField(
            model_name="scenariostechnologies",
            name="col",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="scenariostechnologies",
            name="mult",
            field=models.FloatField(null=True),
        ),
    ]
