# Generated by Django 5.0.1 on 2025-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "siren_web",
            "0093_remove_supplyfactors_col_scenariostechnologies_col_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="direction",
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
