# Generated by Django 5.0.1 on 2025-08-04 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0095_gridlines"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GridLines",
        ),
    ]
