# Generated by Django 5.0.1 on 2025-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0096_delete_gridlines"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridLines",
            fields=[
                ("idgridlines", models.AutoField(primary_key=True, serialize=False)),
                (
                    "line_name",
                    models.CharField(
                        help_text="Unique identifier for the grid line",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "line_code",
                    models.CharField(
                        help_text="Short code for the grid line",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("transmission", "Transmission"),
                            ("distribution", "Distribution"),
                            ("subtransmission", "Sub-transmission"),
                        ],
                        default="transmission",
                        max_length=20,
                    ),
                ),
                ("voltage_level", models.FloatField(help_text="Voltage level in kV")),
                ("length_km", models.FloatField(help_text="Line length in kilometers")),
                (
                    "resistance_per_km",
                    models.FloatField(help_text="Resistance per km (ohms/km)"),
                ),
                (
                    "reactance_per_km",
                    models.FloatField(help_text="Reactance per km (ohms/km)"),
                ),
                (
                    "conductance_per_km",
                    models.FloatField(default=0, help_text="Conductance per km (S/km)"),
                ),
                (
                    "susceptance_per_km",
                    models.FloatField(default=0, help_text="Susceptance per km (S/km)"),
                ),
                (
                    "thermal_capacity_mw",
                    models.FloatField(help_text="Thermal capacity in MW"),
                ),
                (
                    "emergency_capacity_mw",
                    models.FloatField(
                        blank=True, help_text="Emergency capacity in MW", null=True
                    ),
                ),
                (
                    "from_latitude",
                    models.FloatField(help_text="Starting point latitude"),
                ),
                (
                    "from_longitude",
                    models.FloatField(help_text="Starting point longitude"),
                ),
                ("to_latitude", models.FloatField(help_text="Ending point latitude")),
                ("to_longitude", models.FloatField(help_text="Ending point longitude")),
                ("active", models.BooleanField(default=True)),
                ("commissioned_date", models.DateField(blank=True, null=True)),
                ("decommissioned_date", models.DateField(blank=True, null=True)),
                ("owner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "kml_geometry",
                    models.TextField(
                        blank=True,
                        help_text="KML geometry data (stored as text)",
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "GridLines",
                "ordering": ["line_name"],
            },
        ),
    ]
