# Generated by Django 5.0.1 on 2025-08-05 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0097_gridlines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="grid_line",
        ),
        migrations.AddField(
            model_name="facilities",
            name="primary_grid_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_facilities",
                to="siren_web.gridlines",
            ),
        ),
        migrations.AlterField(
            model_name="gridlines",
            name="idgridlines",
            field=models.AutoField(
                db_column="idgridlines", primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="FacilityGridConnections",
            fields=[
                (
                    "idfacilitygridconnections",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Connection"),
                            ("substation", "Via Substation"),
                            ("transformer", "Via Transformer"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "connection_point_latitude",
                    models.FloatField(help_text="Exact connection point latitude"),
                ),
                (
                    "connection_point_longitude",
                    models.FloatField(help_text="Exact connection point longitude"),
                ),
                (
                    "connection_voltage_kv",
                    models.FloatField(help_text="Connection voltage in kV"),
                ),
                (
                    "transformer_capacity_mva",
                    models.FloatField(
                        blank=True,
                        help_text="Transformer capacity if applicable",
                        null=True,
                    ),
                ),
                (
                    "connection_capacity_mw",
                    models.FloatField(help_text="Maximum connection capacity in MW"),
                ),
                (
                    "connection_distance_km",
                    models.FloatField(
                        help_text="Distance from facility to grid connection point"
                    ),
                ),
                ("connection_date", models.DateField(blank=True, null=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the primary grid connection for the facility?",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "idfacilities",
                    models.ForeignKey(
                        db_column="idfacilities",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siren_web.facilities",
                    ),
                ),
                (
                    "idgridlines",
                    models.ForeignKey(
                        db_column="idgridlines",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siren_web.gridlines",
                    ),
                ),
            ],
            options={
                "db_table": "FacilityGridConnections",
                "unique_together": {("idfacilities", "idgridlines", "is_primary")},
            },
        ),
        migrations.AddField(
            model_name="facilities",
            name="grid_connections",
            field=models.ManyToManyField(
                blank=True,
                related_name="connected_facilities",
                through="siren_web.FacilityGridConnections",
                to="siren_web.gridlines",
            ),
        ),
    ]
