# Generated by Django 5.0.1 on 2025-08-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0098_remove_facilities_grid_line_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technologies",
            name="water_usage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Demand",
        ),
    ]
