# Generated by Django 5.0.1 on 2025-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0099_technologies_water_usage_delete_demand"),
    ]

    operations = [
        migrations.CreateModel(
            name="references",
            fields=[
                (
                    "idreferences",
                    models.AutoField(
                        db_column="idreferences", primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, db_column="source", max_length=250, null=True
                    ),
                ),
                ("reference_date", models.DateTimeField(auto_now=True)),
                ("accessed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="location", max_length=250, null=True
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, db_column="section", max_length=250, null=True
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, db_column="notes", max_length=250, null=True
                    ),
                ),
            ],
            options={
                "db_table": "references",
            },
        ),
    ]
