# Generated by Django 5.0.1 on 2025-08-12 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0100_references"),
    ]

    operations = [
        migrations.DeleteModel(
            name="references",
        ),
    ]
