# Generated by Django 5.0.1 on 2025-08-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0102_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "idreferences",
                    models.AutoField(
                        db_column="idreferences", primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source name, URL, or citation", max_length=500
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the referenced work",
                        max_length=300,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author(s) of the referenced work",
                        max_length=200,
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, help_text="When the source was published", null=True
                    ),
                ),
                ("accessed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, help_text="When this reference was last modified"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="URL or physical location", max_length=500
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Specific section, page, or chapter",
                        max_length=250,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this reference"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("web", "Website"),
                            ("book", "Book"),
                            ("journal", "Journal Article"),
                            ("newspaper", "Newspaper"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="web",
                        help_text="Type of reference source",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this reference is still valid/active",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for categorization",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference",
                "verbose_name_plural": "References",
                "db_table": "Reference",
                "ordering": ["-accessed_date"],
            },
        ),
        migrations.DeleteModel(
            name="references",
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["reference_type"], name="Reference_referen_3ed1ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["accessed_date"], name="Reference_accesse_05f8f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["is_active"], name="Reference_is_acti_489b43_idx"
            ),
        ),
    ]
