# Generated by Django 5.0.1 on 2025-08-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0103_reference_delete_references_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("model", "Database Model"),
                            ("module", "Processing Module"),
                            ("external", "External System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "model_class_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=120)),
                ("height", models.IntegerField(default=60)),
                ("color_scheme", models.CharField(default="default", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComponentConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("data_flow", "Data Flow"),
                            ("process_flow", "Process Flow"),
                            ("dependency", "Dependency"),
                        ],
                        default="data_flow",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "from_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="siren_web.systemcomponent",
                    ),
                ),
                (
                    "to_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="siren_web.systemcomponent",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_component", "to_component")},
            },
        ),
    ]
