# Generated by Django 5.0.1 on 2025-08-14 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0104_systemcomponent_componentconnection"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="componentconnection",
            table="ComponentConnection",
        ),
        migrations.AlterModelTable(
            name="systemcomponent",
            table="SystemComponent",
        ),
    ]
