# Generated by Django 5.0.1 on 2025-08-17 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0105_alter_componentconnection_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindTurbines",
            fields=[
                (
                    "idwindturbines",
                    models.AutoField(
                        db_column="idwindturbines", primary_key=True, serialize=False
                    ),
                ),
                (
                    "turbine_model",
                    models.CharField(
                        help_text="Wind turbine model/type (must be unique)",
                        max_length=70,
                        unique=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Turbine manufacturer",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hub_height",
                    models.FloatField(
                        blank=True, help_text="Standard hub height in meters", null=True
                    ),
                ),
                (
                    "rated_power",
                    models.FloatField(
                        blank=True, help_text="Rated power output in kW", null=True
                    ),
                ),
                (
                    "rotor_diameter",
                    models.FloatField(
                        blank=True, help_text="Rotor diameter in meters", null=True
                    ),
                ),
                (
                    "cut_in_speed",
                    models.FloatField(
                        blank=True, help_text="Cut-in wind speed in m/s", null=True
                    ),
                ),
                (
                    "cut_out_speed",
                    models.FloatField(
                        blank=True, help_text="Cut-out wind speed in m/s", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wind Turbine Model",
                "verbose_name_plural": "Wind Turbine Models",
                "db_table": "WindTurbines",
            },
        ),
        migrations.CreateModel(
            name="FacilityWindTurbines",
            fields=[
                (
                    "idfacilitywindturbines",
                    models.AutoField(
                        db_column="idfacilitywindturbines",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "no_turbines",
                    models.IntegerField(
                        help_text="Number of this turbine model at this facility"
                    ),
                ),
                (
                    "tilt",
                    models.IntegerField(
                        blank=True, help_text="Turbine tilt angle in degrees", null=True
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        help_text="Primary wind direction or turbine orientation",
                        max_length=28,
                        null=True,
                    ),
                ),
                (
                    "installation_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when these turbines were installed",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether these turbines are currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this turbine installation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idfacilities",
                    models.ForeignKey(
                        db_column="idfacilities",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siren_web.facilities",
                    ),
                ),
                (
                    "idwindturbines",
                    models.ForeignKey(
                        db_column="idwindturbines",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siren_web.windturbines",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Wind Turbine Installation",
                "verbose_name_plural": "Facility Wind Turbine Installations",
                "db_table": "FacilityWindTurbines",
                "unique_together": {("idfacilities", "idwindturbines")},
            },
        ),
        migrations.AddField(
            model_name="facilities",
            name="wind_turbines",
            field=models.ManyToManyField(
                blank=True,
                related_name="connected_turbines",
                through="siren_web.FacilityWindTurbines",
                to="siren_web.windturbines",
            ),
        ),
        migrations.CreateModel(
            name="TurbinePowerCurves",
            fields=[
                (
                    "idturbinepowercurves",
                    models.AutoField(
                        db_column="idturbinepowercurves",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "power_file_name",
                    models.CharField(
                        help_text="Original .pow file name", max_length=45
                    ),
                ),
                (
                    "power_curve_data",
                    models.JSONField(
                        help_text="JSON stored power curve data from .pow file"
                    ),
                ),
                ("file_upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this power curve is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this power curve",
                        null=True,
                    ),
                ),
                (
                    "idwindturbines",
                    models.ForeignKey(
                        db_column="idwindturbines",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_curves",
                        to="siren_web.windturbines",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turbine Power Curve",
                "verbose_name_plural": "Turbine Power Curves",
                "db_table": "TurbinePowerCurves",
                "ordering": ["-file_upload_date"],
                "unique_together": {("idwindturbines", "power_file_name")},
            },
        ),
    ]
