# Generated by Django 5.0.1 on 2025-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0106_windturbines_facilitywindturbines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="windturbines",
            name="application",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onshore", "Onshore"),
                    ("offshore", "Offshore"),
                    ("floating", "Floating"),
                ],
                help_text="Turbine application type",
                max_length=20,
                null=True,
            ),
        ),
    ]
