# Generated by Django 5.0.1 on 2025-09-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0107_windturbines_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Terminals",
            fields=[
                (
                    "idterminals",
                    models.AutoField(
                        db_column="idterminals", primary_key=True, serialize=False
                    ),
                ),
                (
                    "terminal_name",
                    models.CharField(
                        help_text="Unique name for the terminal",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "terminal_code",
                    models.CharField(
                        help_text="Short code for the terminal",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "terminal_type",
                    models.CharField(
                        choices=[
                            ("substation", "Substation"),
                            ("switching_station", "Switching Station"),
                            ("distribution_substation", "Distribution Substation"),
                            ("transmission_substation", "Transmission Substation"),
                            ("converter_station", "Converter Station"),
                            ("terminal_station", "Terminal Station"),
                        ],
                        default="substation",
                        max_length=30,
                    ),
                ),
                ("latitude", models.FloatField(help_text="Terminal latitude")),
                ("longitude", models.FloatField(help_text="Terminal longitude")),
                (
                    "elevation",
                    models.FloatField(
                        blank=True,
                        help_text="Elevation above sea level in meters",
                        null=True,
                    ),
                ),
                (
                    "primary_voltage_kv",
                    models.FloatField(help_text="Primary voltage level in kV"),
                ),
                (
                    "secondary_voltage_kv",
                    models.FloatField(
                        blank=True, help_text="Secondary voltage level in kV", null=True
                    ),
                ),
                (
                    "voltage_class",
                    models.CharField(
                        choices=[
                            ("low", "Low Voltage (< 1kV)"),
                            ("medium", "Medium Voltage (1-35kV)"),
                            ("high", "High Voltage (35-138kV)"),
                            ("extra_high", "Extra High Voltage (138-800kV)"),
                            ("ultra_high", "Ultra High Voltage (> 800kV)"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                (
                    "transformer_capacity_mva",
                    models.FloatField(
                        blank=True,
                        help_text="Total transformer capacity in MVA",
                        null=True,
                    ),
                ),
                (
                    "short_circuit_capacity_mva",
                    models.FloatField(
                        blank=True, help_text="Short circuit capacity in MVA", null=True
                    ),
                ),
                (
                    "bay_count",
                    models.IntegerField(
                        blank=True, help_text="Number of bays/feeders", null=True
                    ),
                ),
                ("commissioned_date", models.DateField(blank=True, null=True)),
                ("decommissioned_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("owner", models.CharField(blank=True, max_length=100, null=True)),
                ("operator", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "maintenance_zone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "control_center",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "scada_id",
                    models.CharField(
                        blank=True,
                        help_text="SCADA system identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Terminal",
                "verbose_name_plural": "Terminals",
                "db_table": "Terminals",
                "ordering": ["terminal_name"],
            },
        ),
        migrations.AddField(
            model_name="gridlines",
            name="from_terminal",
            field=models.ForeignKey(
                blank=True,
                help_text="Terminal where this line originates",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_lines",
                to="siren_web.terminals",
            ),
        ),
        migrations.AddField(
            model_name="gridlines",
            name="to_terminal",
            field=models.ForeignKey(
                blank=True,
                help_text="Terminal where this line terminates",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_lines",
                to="siren_web.terminals",
            ),
        ),
    ]
