# Generated by Django 5.0.1 on 2025-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0108_terminals_gridlines_from_terminal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridlines",
            name="ga_guid",
            field=models.CharField(
                help_text="Unique identifier", max_length=40, null=True, unique=True
            ),
        ),
    ]
