# Generated by Django 5.0.1 on 2025-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0109_gridlines_ga_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridlines",
            name="is_aboveground",
            field=models.BooleanField(default=True),
        ),
    ]
