# Generated by Django 5.0.1 on 2025-10-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "siren_web",
            "0111_facilitymetadata_loadanalysissummary_dpvgeneration_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityScada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_interval", models.DateTimeField(db_index=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        db_column="idfacilities",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scada_records",
                        to="siren_web.facilities",
                    ),
                ),
            ],
            options={
                "db_table": "facility_scadax",
                "ordering": ["-dispatch_interval", "facility"],
                "indexes": [
                    models.Index(
                        fields=["dispatch_interval", "facility"],
                        name="facility_sc_dispatc_410868_idx",
                    ),
                    models.Index(
                        fields=["dispatch_interval"],
                        name="facility_sc_dispatc_156ee9_idx",
                    ),
                    models.Index(
                        fields=["facility", "dispatch_interval"],
                        name="facility_sc_idfacil_c8e062_idx",
                    ),
                ],
                "unique_together": {("dispatch_interval", "facility")},
            },
        ),
    ]
