# Generated by Django 5.0.1 on 2025-10-07 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0112_facilityscadax"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="facilityscada",
            new_name="facility_sc_dispatc_89754e_idx",
            old_name="facility_sc_dispatc_410868_idx",
        ),
        migrations.RenameIndex(
            model_name="facilityscada",
            new_name="facility_sc_dispatc_d6b884_idx",
            old_name="facility_sc_dispatc_156ee9_idx",
        ),
        migrations.RenameIndex(
            model_name="facilityscada",
            new_name="facility_sc_idfacil_24b98f_idx",
            old_name="facility_sc_idfacil_c8e062_idx",
        ),
        migrations.AlterModelTable(
            name="facilityscada",
            table="facility_scada",
        ),
    ]
