# Generated by Django 5.0.1 on 2025-10-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "siren_web",
            "0113_rename_facility_sc_dispatc_410868_idx_facility_sc_dispatc_89754e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generatorattributes",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WIND", "Wind"),
                    ("SOLAR", "Solar"),
                    ("GAS", "Gas"),
                    ("COAL", "Coal"),
                    ("HYDRO", "Hydro"),
                    ("BIOMASS", "Biomass"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="capacities",
        ),
    ]
