# Generated by Django 5.0.1 on 2025-10-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0114_generatorattributes_fuel_type_delete_capacities"),
    ]

    operations = [
        migrations.CreateModel(
            name="WholesalePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True)),
                ("interval_number", models.IntegerField()),
                ("trading_interval", models.DateTimeField(db_index=True)),
                ("wholesale_price", models.FloatField()),
                ("extracted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "WholesalePrice",
                "ordering": ["-trading_date", "interval_number"],
                "indexes": [
                    models.Index(
                        fields=["trading_date", "interval_number"],
                        name="WholesalePr_trading_c78a4c_idx",
                    ),
                    models.Index(
                        fields=["trading_interval"],
                        name="WholesalePr_trading_2b4d48_idx",
                    ),
                ],
                "unique_together": {("trading_date", "interval_number")},
            },
        ),
    ]
