# Generated by Django 5.0.1 on 2025-10-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0115_wholesaleprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatorattributes",
            name="fuel_type",
        ),
        migrations.AddField(
            model_name="technologies",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WIND", "Wind"),
                    ("SOLAR", "Solar"),
                    ("GAS", "Gas"),
                    ("COAL", "Coal"),
                    ("HYDRO", "Hydro"),
                    ("BIOMASS", "Biomass"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
