# Generated by Django 5.2.7 on 2025-11-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0116_remove_generatorattributes_fuel_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacilityMetadata",
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="auxiliary_load",
            field=models.FloatField(help_text="MW - parasitic load", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="charge_efficiency",
            field=models.FloatField(help_text="Decimal, e.g., 0.92", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="cycle_life",
            field=models.IntegerField(help_text="Full cycle equivalents", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="degradation_rate",
            field=models.FloatField(help_text="% per year", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="discharge_efficiency",
            field=models.FloatField(help_text="Decimal, e.g., 0.92", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="duration",
            field=models.FloatField(help_text="Hours at rated power", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="energy_capacity",
            field=models.FloatField(help_text="MWh - total storage", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="initial_state_of_charge",
            field=models.FloatField(default=0.5, help_text="Starting SOC"),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="max_state_of_charge",
            field=models.FloatField(default=1.0, help_text="Maximum SOC (0-1)"),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="min_state_of_charge",
            field=models.FloatField(default=0.0, help_text="Minimum SOC (0-1)"),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="power_capacity",
            field=models.FloatField(
                help_text="MW - max charge/discharge rate", null=True
            ),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="round_trip_efficiency",
            field=models.FloatField(help_text="Decimal, e.g., 0.85", null=True),
        ),
        migrations.AddField(
            model_name="storageattributes",
            name="self_discharge_rate",
            field=models.FloatField(help_text="% per hour", null=True),
        ),
    ]
