# Generated by Django 5.2.7 on 2025-11-01 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0117_delete_facilitymetadata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storageattributes",
            options={
                "verbose_name": "Storage Attribute",
                "verbose_name_plural": "Storage Attributes",
            },
        ),
    ]
