# Generated by Django 5.2.7 on 2025-11-02 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0118_alter_storageattributes_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storageattributes",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="energy_capacity",
        ),
        migrations.RemoveField(
            model_name="storageattributes",
            name="power_capacity",
        ),
        migrations.CreateModel(
            name="FacilityStorage",
            fields=[
                (
                    "idfacilitystorage",
                    models.AutoField(
                        db_column="idfacilitystorage", primary_key=True, serialize=False
                    ),
                ),
                (
                    "power_capacity",
                    models.FloatField(
                        blank=True,
                        help_text="MW - max charge/discharge rate at this facility",
                        null=True,
                    ),
                ),
                (
                    "energy_capacity",
                    models.FloatField(
                        blank=True,
                        help_text="MWh - total storage capacity at this facility",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True,
                        help_text="Hours at rated power for this installation",
                        null=True,
                    ),
                ),
                (
                    "installation_name",
                    models.CharField(
                        blank=True,
                        help_text='Name for this storage installation (e.g., "Main Battery Bank")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "installation_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this storage system was installed",
                        null=True,
                    ),
                ),
                (
                    "commissioning_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when storage system began operations",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this storage installation is currently active",
                    ),
                ),
                (
                    "initial_state_of_charge",
                    models.FloatField(
                        blank=True,
                        help_text="Initial SOC for this installation (0.0 to 1.0), overrides technology default if set",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this storage installation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idfacilities",
                    models.ForeignKey(
                        db_column="idfacilities",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_installations",
                        to="siren_web.facilities",
                    ),
                ),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        db_column="idtechnologies",
                        limit_choices_to={"category": "Storage"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_installations",
                        to="siren_web.technologies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Storage Installation",
                "verbose_name_plural": "Facility Storage Installations",
                "db_table": "FacilityStorage",
                "ordering": ["idfacilities", "idtechnologies"],
                "unique_together": {
                    ("idfacilities", "idtechnologies", "installation_name")
                },
            },
        ),
    ]
