# Generated by Django 5.2.7 on 2025-11-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0119_remove_storageattributes_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarAttributes",
            fields=[
                (
                    "idsolarattributes",
                    models.AutoField(
                        db_column="idSolarAttributes", primary_key=True, serialize=False
                    ),
                ),
                (
                    "module_efficiency",
                    models.FloatField(
                        blank=True,
                        help_text="Module efficiency as decimal (e.g., 0.20 for 20%)",
                        null=True,
                    ),
                ),
                (
                    "temperature_coefficient",
                    models.FloatField(
                        blank=True,
                        help_text="Temperature coefficient of power (%/°C, typically -0.3 to -0.5)",
                        null=True,
                    ),
                ),
                (
                    "nominal_operating_cell_temp",
                    models.FloatField(
                        blank=True,
                        help_text="NOCT in °C (typically 42-46°C)",
                        null=True,
                    ),
                ),
                (
                    "inverter_efficiency",
                    models.FloatField(
                        blank=True,
                        help_text="Inverter efficiency as decimal (e.g., 0.98)",
                        null=True,
                    ),
                ),
                (
                    "system_loss_factor",
                    models.FloatField(
                        blank=True,
                        help_text="Combined system losses as decimal (soiling, wiring, mismatch, etc.)",
                        null=True,
                    ),
                ),
                (
                    "dc_ac_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="DC to AC ratio (typically 1.1 to 1.3)",
                        null=True,
                    ),
                ),
                (
                    "performance_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="System performance ratio (PR) as decimal (typically 0.75-0.85)",
                        null=True,
                    ),
                ),
                (
                    "capacity_factor_typical",
                    models.FloatField(
                        blank=True,
                        help_text="Typical capacity factor for this technology (location-dependent)",
                        null=True,
                    ),
                ),
                (
                    "degradation_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Annual degradation rate as decimal (typically 0.005 = 0.5%/year)",
                        null=True,
                    ),
                ),
                (
                    "warranty_years",
                    models.IntegerField(
                        blank=True,
                        help_text="Panel warranty period in years",
                        null=True,
                    ),
                ),
                (
                    "panel_technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monocrystalline", "Monocrystalline Silicon"),
                            ("polycrystalline", "Polycrystalline Silicon"),
                            ("thin_film", "Thin Film"),
                            ("cigs", "CIGS"),
                            ("cdte", "CdTe"),
                            ("perc", "PERC"),
                            ("bifacial", "Bifacial"),
                            ("tandem", "Tandem/Multi-junction"),
                        ],
                        help_text="Type of solar panel technology",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Tilt"),
                            ("single_axis", "Single-Axis Tracking"),
                            ("dual_axis", "Dual-Axis Tracking"),
                        ],
                        default="fixed",
                        help_text="Type of tracking system",
                        max_length=20,
                    ),
                ),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        blank=True,
                        db_column="idTechnologies",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_attributes",
                        to="siren_web.technologies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solar Attribute",
                "verbose_name_plural": "Solar Attributes",
                "db_table": "SolarAttributes",
            },
        ),
        migrations.CreateModel(
            name="FacilitySolar",
            fields=[
                (
                    "idfacilitysolar",
                    models.AutoField(
                        db_column="idfacilitysolar", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nameplate_capacity",
                    models.FloatField(
                        blank=True, help_text="MW - DC nameplate capacity", null=True
                    ),
                ),
                (
                    "ac_capacity",
                    models.FloatField(
                        blank=True,
                        help_text="MW - AC capacity (inverter rating)",
                        null=True,
                    ),
                ),
                (
                    "panel_count",
                    models.IntegerField(
                        blank=True, help_text="Total number of solar panels", null=True
                    ),
                ),
                (
                    "panel_wattage",
                    models.FloatField(
                        blank=True,
                        help_text="Watts - Individual panel rating",
                        null=True,
                    ),
                ),
                (
                    "tilt_angle",
                    models.FloatField(
                        blank=True,
                        help_text="Degrees - Panel tilt angle from horizontal",
                        null=True,
                    ),
                ),
                (
                    "azimuth_angle",
                    models.FloatField(
                        blank=True,
                        help_text="Degrees - Panel azimuth (0=North, 90=East, 180=South, 270=West)",
                        null=True,
                    ),
                ),
                (
                    "array_area",
                    models.FloatField(
                        blank=True,
                        help_text="Square meters - Total panel array area",
                        null=True,
                    ),
                ),
                (
                    "installation_name",
                    models.CharField(
                        blank=True,
                        help_text='Name for this solar installation (e.g., "East Array")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "installation_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when solar system was installed",
                        null=True,
                    ),
                ),
                (
                    "commissioning_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when solar system began operations",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this solar installation is currently active",
                    ),
                ),
                (
                    "inverter_count",
                    models.IntegerField(
                        blank=True, help_text="Number of inverters", null=True
                    ),
                ),
                (
                    "inverter_capacity_each",
                    models.FloatField(
                        blank=True,
                        help_text="kW - Capacity of each inverter",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this solar installation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idfacilities",
                    models.ForeignKey(
                        db_column="idfacilities",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_installations",
                        to="siren_web.facilities",
                    ),
                ),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        db_column="idtechnologies",
                        limit_choices_to={"category": "Solar"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_facility_installations",
                        to="siren_web.technologies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Solar Installation",
                "verbose_name_plural": "Facility Solar Installations",
                "db_table": "FacilitySolar",
                "ordering": ["idfacilities", "idtechnologies"],
                "unique_together": {
                    ("idfacilities", "idtechnologies", "installation_name")
                },
            },
        ),
    ]
