# Generated by Django 5.2.7 on 2025-11-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0120_solarattributes_facilitysolar"),
    ]

    operations = [
        migrations.CreateModel(
            name="HybridSolarStorage",
            fields=[
                (
                    "idhybridsolarstorstorage",
                    models.AutoField(
                        db_column="idhybridsolarstorstorage",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "coupling_type",
                    models.CharField(
                        choices=[
                            ("dc_coupled", "DC-Coupled"),
                            ("ac_coupled", "AC-Coupled"),
                        ],
                        default="dc_coupled",
                        help_text="DC-coupled shares inverter, AC-coupled has separate inverters",
                        max_length=20,
                    ),
                ),
                (
                    "shared_grid_connection",
                    models.BooleanField(
                        default=True,
                        help_text="Whether solar and storage share the same grid connection point",
                    ),
                ),
                (
                    "shared_inverter_capacity",
                    models.FloatField(
                        blank=True,
                        help_text="MW - Shared inverter capacity for DC-coupled systems",
                        null=True,
                    ),
                ),
                (
                    "grid_connection_capacity",
                    models.FloatField(
                        blank=True,
                        help_text="MW - Maximum capacity at point of interconnection (POI)",
                        null=True,
                    ),
                ),
                (
                    "charge_from_solar_only",
                    models.BooleanField(
                        default=True,
                        help_text="Battery charges only from solar (not from grid)",
                    ),
                ),
                (
                    "priority_dispatch",
                    models.CharField(
                        choices=[
                            ("solar_first", "Solar First (export excess)"),
                            ("battery_first", "Battery First (charge then export)"),
                            ("balanced", "Balanced (optimize based on signals)"),
                        ],
                        default="battery_first",
                        help_text="Dispatch priority strategy",
                        max_length=20,
                    ),
                ),
                (
                    "configuration_name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this hybrid configuration",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "commissioning_date",
                    models.DateField(
                        blank=True,
                        help_text="When hybrid system began combined operations",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether hybrid configuration is currently active",
                    ),
                ),
                (
                    "energy_clipping_losses",
                    models.FloatField(
                        blank=True,
                        help_text="% - Energy losses due to inverter clipping in DC-coupled systems",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about hybrid configuration",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "solar_installation",
                    models.ForeignKey(
                        db_column="idfacilitysolar",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_configurations",
                        to="siren_web.facilitysolar",
                    ),
                ),
                (
                    "storage_installation",
                    models.ForeignKey(
                        db_column="idfacilitystorage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_configurations",
                        to="siren_web.facilitystorage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hybrid Solar+Storage Configuration",
                "verbose_name_plural": "Hybrid Solar+Storage Configurations",
                "db_table": "HybridSolarStorage",
                "unique_together": {("solar_installation", "storage_installation")},
            },
        ),
    ]
