# Generated by Django 5.2.7 on 2025-11-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0121_hybridsolarstorage"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="emission_intensity",
            field=models.FloatField(null=True),
        ),
    ]
