# Generated by Django 5.2.7 on 2025-11-20 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0122_facilities_emission_intensity"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenewableEnergyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_year", models.IntegerField(db_index=True, unique=True)),
                (
                    "target_percentage",
                    models.FloatField(help_text="Target RE% for this year"),
                ),
                (
                    "target_emissions_tonnes",
                    models.FloatField(
                        blank=True,
                        help_text="Target emissions in tonnes CO2-e",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "is_interim_target",
                    models.BooleanField(
                        default=False, help_text="Is this an interim milestone?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "renewable_energy_targets",
                "ordering": ["target_year"],
            },
        ),
        migrations.CreateModel(
            name="TargetScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_name", models.CharField(max_length=100, unique=True)),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("base_case", "Base Case"),
                            ("high_electrification", "High Electrification"),
                            ("delayed_pipeline", "Delayed Pipeline"),
                            ("accelerated_pipeline", "Accelerated Pipeline"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("projected_re_percentage_2030", models.FloatField()),
                ("projected_emissions_2030_tonnes", models.FloatField()),
                ("wind_generation_2030", models.FloatField()),
                ("solar_generation_2030", models.FloatField()),
                ("dpv_generation_2030", models.FloatField()),
                ("biomass_hydro_generation_2030", models.FloatField()),
                ("gas_generation_2030", models.FloatField()),
                ("gas_ocgt_generation_2030", models.FloatField()),
                (
                    "probability_percentage",
                    models.FloatField(
                        blank=True, help_text="Monte Carlo probability (%)", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "target_scenarios",
                "ordering": ["scenario_type"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyREPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "month",
                    models.IntegerField(db_index=True, help_text="Month number (1-12)"),
                ),
                (
                    "total_generation",
                    models.FloatField(help_text="Total grid generation in GWh"),
                ),
                (
                    "operational_demand",
                    models.FloatField(help_text="Operational demand in GWh"),
                ),
                (
                    "underlying_demand",
                    models.FloatField(
                        help_text="Underlying demand (includes rooftop) in GWh"
                    ),
                ),
                ("wind_generation", models.FloatField(default=0)),
                ("solar_generation", models.FloatField(default=0)),
                ("dpv_generation", models.FloatField(default=0)),
                ("biomass_generation", models.FloatField(default=0)),
                ("hydro_generation", models.FloatField(default=0)),
                (
                    "gas_generation",
                    models.FloatField(
                        default=0, help_text="Combined Cycle Gas Turbine"
                    ),
                ),
                (
                    "gas_ocgt_generation",
                    models.FloatField(default=0, help_text="Open Cycle Gas Turbine"),
                ),
                ("coal_generation", models.FloatField(default=0)),
                ("storage_discharge", models.FloatField(default=0)),
                ("storage_charge", models.FloatField(default=0)),
                (
                    "total_emissions_tonnes",
                    models.FloatField(help_text="Total emissions in tonnes CO2-e"),
                ),
                (
                    "emissions_intensity_kg_mwh",
                    models.FloatField(
                        help_text="Grid emissions intensity kg CO2-e/MWh"
                    ),
                ),
                ("peak_demand_mw", models.FloatField(blank=True, null=True)),
                ("peak_demand_datetime", models.DateTimeField(blank=True, null=True)),
                ("minimum_demand_mw", models.FloatField(blank=True, null=True)),
                (
                    "minimum_demand_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("best_re_hour_percentage", models.FloatField(blank=True, null=True)),
                ("best_re_hour_datetime", models.DateTimeField(blank=True, null=True)),
                ("data_complete", models.BooleanField(default=False)),
                ("data_source", models.CharField(default="SCADA", max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "monthly_re_performance",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="monthly_re__year_e3620f_idx"
                    ),
                    models.Index(
                        fields=["-year", "-month"], name="monthly_re__year_42e001_idx"
                    ),
                ],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="NewCapacityCommissioned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commissioned_date", models.DateField()),
                ("capacity_mw", models.FloatField(help_text="Capacity in MW")),
                ("technology_type", models.CharField(max_length=50)),
                ("report_year", models.IntegerField()),
                ("report_month", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("commissioned", "Commissioned"),
                            ("under_construction", "Under Construction"),
                            ("planned", "Planned"),
                            ("probable", "Probable"),
                            ("possible", "Possible"),
                        ],
                        default="commissioned",
                        max_length=20,
                    ),
                ),
                (
                    "expected_commissioning_date",
                    models.DateField(
                        blank=True, help_text="For future projects", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissioning_records",
                        to="siren_web.facilities",
                    ),
                ),
            ],
            options={
                "db_table": "new_capacity_commissioned",
                "ordering": ["-commissioned_date"],
                "indexes": [
                    models.Index(
                        fields=["commissioned_date"],
                        name="new_capacit_commiss_149fd9_idx",
                    ),
                    models.Index(
                        fields=["report_year", "report_month"],
                        name="new_capacit_report__43ce52_idx",
                    ),
                ],
            },
        ),
    ]
