# Generated by Django 5.2.7 on 2025-11-21 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0123_renewableenergytarget_targetscenario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="targetscenario",
            old_name="biomass_hydro_generation_2030",
            new_name="biomass_hydro_generation_2040",
        ),
        migrations.RenameField(
            model_name="targetscenario",
            old_name="gas_generation_2030",
            new_name="gas_generation_2040",
        ),
        migrations.RenameField(
            model_name="targetscenario",
            old_name="gas_ocgt_generation_2030",
            new_name="gas_ocgt_generation_2040",
        ),
        migrations.RenameField(
            model_name="targetscenario",
            old_name="projected_emissions_2030_tonnes",
            new_name="projected_emissions_2040_tonnes",
        ),
        migrations.RenameField(
            model_name="targetscenario",
            old_name="projected_re_percentage_2030",
            new_name="projected_re_percentage_2040",
        ),
        migrations.RenameField(
            model_name="targetscenario",
            old_name="dpv_generation_2030",
            new_name="dpv_generation_2040",
        ),
        migrations.RenameField(
            model_name="targetscenario",
            old_name="solar_generation_2030",
            new_name="solar_generation_2040",
        ),
        migrations.RenameField(
            model_name="targetscenario",
            old_name="wind_generation_2030",
            new_name="wind_generation_2040",
        ),
    ]
