# Generated by Django 5.2.7 on 2025-11-25 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "siren_web",
            "0124_rename_biomass_hydro_generation_2030_targetscenario_biomass_hydro_generation_2040_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyreperformance",
            name="gas_ocgt_generation",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="gas_ocgt_generation_2040",
        ),
    ]
