# Generated by Django 5.2.7 on 2025-11-25 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0125_remove_monthlyreperformance_gas_ocgt_generation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="targetscenario",
            old_name="biomass_hydro_generation_2040",
            new_name="biomass_generation_2040",
        ),
    ]
