# Generated by Django 5.2.7 on 2025-11-30 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "siren_web",
            "0126_rename_biomass_hydro_generation_2040_targetscenario_biomass_generation_2040",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="TradingPrice",
        ),
        migrations.RemoveField(
            model_name="monthlyreperformance",
            name="hydro_generation",
        ),
    ]
