# Generated by Django 5.2.7 on 2025-12-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0127_delete_tradingprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_negative_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of trading intervals with negative prices",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_price_avg",
            field=models.FloatField(
                blank=True,
                help_text="Average wholesale price ($/MWh) for the month",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_price_max",
            field=models.FloatField(
                blank=True,
                help_text="Maximum wholesale price ($/MWh) for the month",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_price_max_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Date/time of maximum wholesale price", null=True
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_price_min",
            field=models.FloatField(
                blank=True,
                help_text="Minimum wholesale price ($/MWh) for the month",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_price_min_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Date/time of minimum wholesale price", null=True
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_price_std_dev",
            field=models.FloatField(
                blank=True,
                help_text="Standard deviation of wholesale prices ($/MWh)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="wholesale_spike_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of trading intervals with prices > $300/MWh",
                null=True,
            ),
        ),
    ]
