# Generated by Django 5.2.7 on 2025-12-06 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0128_monthlyreperformance_wholesale_negative_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="generation",
        ),
        migrations.RemoveField(
            model_name="facilities",
            name="transmitted",
        ),
    ]
