# Generated by Django 5.2.7 on 2025-12-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0129_remove_facilities_generation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="hub_height",
        ),
        migrations.RemoveField(
            model_name="facilities",
            name="no_turbines",
        ),
        migrations.RemoveField(
            model_name="facilities",
            name="tilt",
        ),
        migrations.RemoveField(
            model_name="facilities",
            name="turbine",
        ),
        migrations.AlterField(
            model_name="targetscenario",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("base_case", "Base Case"),
                    ("delayed_pipeline", "Delayed Pipeline"),
                    ("accelerated_pipeline", "Accelerated Pipeline"),
                ],
                max_length=30,
            ),
        ),
    ]
