# Generated by Django 5.2.7 on 2025-12-11 01:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0130_remove_facilities_hub_height_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Dashboard"),
                            ("quarterly", "Quarterly Report"),
                            ("annual", "Annual Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        blank=True,
                        help_text="Required for monthly reports",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        blank=True,
                        help_text="Required for quarterly reports",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Stored separately in case user is deleted",
                        max_length=100,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("observation", "Observation"),
                            ("question", "Question"),
                            ("action_item", "Action Item"),
                            ("correction", "Correction"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Pinned comments appear at top"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Mark action items/questions as resolved",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ret_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "year", "month"],
                        name="siren_web_r_report__50d1ba_idx",
                    ),
                    models.Index(
                        fields=["report_type", "year", "quarter"],
                        name="siren_web_r_report__cd1a23_idx",
                    ),
                    models.Index(
                        fields=["report_type", "year"],
                        name="siren_web_r_report__f25af2_idx",
                    ),
                ],
            },
        ),
    ]
