# Generated by Django 5.2.7 on 2025-12-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0132_executivesummary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilitywindturbines",
            options={
                "ordering": ["idfacilities", "commissioning_date"],
                "verbose_name": "Facility Wind Turbine Installation",
                "verbose_name_plural": "Facility Wind Turbine Installations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="facilitywindturbines",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="facilitywindturbines",
            name="commissioning_date",
            field=models.DateField(
                blank=True,
                help_text="Date when these turbines began operations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facilitywindturbines",
            name="hub_height_override",
            field=models.FloatField(
                blank=True,
                help_text="Override hub height (m) if different from turbine default",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facilitywindturbines",
            name="idtechnologies",
            field=models.ForeignKey(
                blank=True,
                db_column="idtechnologies",
                help_text="Wind technology type (e.g., Onshore Wind, Offshore Wind)",
                limit_choices_to={"category": "Wind"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wind_facility_installations",
                to="siren_web.technologies",
            ),
        ),
        migrations.AddField(
            model_name="facilitywindturbines",
            name="installation_name",
            field=models.CharField(
                blank=True,
                help_text="Name for this installation (e.g., 'Phase 1', 'North Array')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facilitywindturbines",
            name="nameplate_capacity",
            field=models.FloatField(
                blank=True,
                help_text="MW - Override capacity. If null, calculated from turbine count × rated power",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="capacity",
            field=models.FloatField(
                blank=True,
                help_text="Override total capacity (MW). If null, computed from installations.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="capacityfactor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="idtechnologies",
            field=models.ForeignKey(
                blank=True,
                db_column="idtechnologies",
                help_text="DEPRECATED: Use installation models instead. Kept for migration.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="legacy_facilities",
                to="siren_web.technologies",
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="storage_hours",
            field=models.FloatField(
                blank=True,
                help_text="DEPRECATED: Use FacilityStorage installations instead.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facilitysolar",
            name="installation_name",
            field=models.CharField(
                blank=True,
                help_text='Name for this solar installation (e.g., "East Array", "Phase 2")',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facilitystorage",
            name="installation_name",
            field=models.CharField(
                blank=True,
                help_text='Name for this storage installation (e.g., "Main Battery Bank", "Phase 2")',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facilitywindturbines",
            name="no_turbines",
            field=models.IntegerField(
                help_text="Number of this turbine model in this installation"
            ),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("observation", "Observation"),
                    ("question", "Question"),
                    ("action_item", "Action Item"),
                    ("correction", "Correction"),
                    ("executive_summary", "Executive Summary"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="storageattributes",
            name="idtechnologies",
            field=models.ForeignKey(
                blank=True,
                db_column="idTechnologies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_attributes",
                to="siren_web.technologies",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="facilitywindturbines",
            unique_together={("idfacilities", "idwindturbines", "installation_name")},
        ),
        migrations.DeleteModel(
            name="ExecutiveSummary",
        ),
    ]
