# Generated by Django 5.2.7 on 2025-12-14 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0133_alter_facilitywindturbines_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComponentConnection",
        ),
        migrations.DeleteModel(
            name="SystemComponent",
        ),
    ]
