# Generated by Django 5.2.7 on 2025-12-14 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0134_delete_componentconnection_delete_systemcomponent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HybridSolarStorage",
        ),
    ]
