# Generated by Django 5.2.7 on 2025-12-17 05:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0135_delete_hybridsolarstorage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandFactorType",
            fields=[
                (
                    "iddemandfactortype",
                    models.AutoField(
                        db_column="iddemandfactortype",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Factor name (e.g., 'EV Adoption')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this demand factor",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("operational", "Operational Demand Only"),
                            ("underlying", "Underlying Demand Only"),
                            ("both", "Both Operational and Underlying"),
                        ],
                        default="both",
                        help_text="Which demand type this factor applies to",
                        max_length=20,
                    ),
                ),
                (
                    "is_system_default",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a system-provided factor type",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for displaying in UI (lower numbers first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Demand Factor Type",
                "verbose_name_plural": "Demand Factor Types",
                "db_table": "demandfactortype",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DemandProjectionScenario",
            fields=[
                (
                    "iddemandprojectionscenario",
                    models.AutoField(
                        db_column="iddemandprojectionscenario",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_year",
                    models.IntegerField(
                        default=2024, help_text="Base year for demand projections"
                    ),
                ),
                (
                    "projection_end_year",
                    models.IntegerField(
                        default=2050, help_text="Final year of projection"
                    ),
                ),
                (
                    "use_factor_breakdown",
                    models.BooleanField(
                        default=True,
                        help_text="Use factor-based projections (vs legacy simple rates)",
                    ),
                ),
                (
                    "simple_operational_rate",
                    models.FloatField(
                        blank=True,
                        help_text="DEPRECATED: Simple operational growth rate (use factors instead)",
                        null=True,
                    ),
                ),
                (
                    "simple_underlying_rate",
                    models.FloatField(
                        blank=True,
                        help_text="DEPRECATED: Simple underlying growth rate (use factors instead)",
                        null=True,
                    ),
                ),
                (
                    "require_100_percent",
                    models.BooleanField(
                        default=False,
                        help_text="Require factor percentages to sum to exactly 100%",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this projection configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.OneToOneField(
                        db_column="idscenarios",
                        help_text="Link to main scenario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_projection_config",
                        to="siren_web.scenarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Projection Scenario",
                "verbose_name_plural": "Demand Projection Scenarios",
                "db_table": "demandprojectionscenario",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DemandFactor",
            fields=[
                (
                    "iddemandfactor",
                    models.AutoField(
                        db_column="iddemandfactor", primary_key=True, serialize=False
                    ),
                ),
                (
                    "base_year",
                    models.IntegerField(
                        default=2024, help_text="Starting year for projections"
                    ),
                ),
                (
                    "base_percentage_operational",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of total operational demand in base year (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "base_percentage_underlying",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of total underlying demand in base year (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "growth_rate",
                    models.FloatField(
                        default=0.02,
                        help_text="Annual growth rate (e.g., 0.03 for 3% growth)",
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "growth_type",
                    models.CharField(
                        choices=[
                            ("linear", "Linear Growth"),
                            ("exponential", "Exponential Growth"),
                            ("s_curve", "S-Curve (Logistic)"),
                            ("compound", "Compound Annual Growth"),
                        ],
                        default="exponential",
                        help_text="Mathematical model for growth",
                        max_length=20,
                    ),
                ),
                (
                    "saturation_multiplier",
                    models.FloatField(
                        default=2.0,
                        help_text="Maximum growth multiplier for S-curve (e.g., 2.0 = doubles at saturation)",
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "midpoint_year",
                    models.IntegerField(
                        default=2035,
                        help_text="Year where S-curve reaches 50% of saturation",
                    ),
                ),
                (
                    "time_varying_config",
                    models.JSONField(
                        blank=True,
                        help_text='Time-varying rates as JSON: {"2025": 0.03, "2030": 0.05}. Year keys must be strings.',
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this factor is included in projections",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this factor configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        db_column="idscenarios",
                        help_text="Scenario this factor belongs to (null = default/template)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_factors",
                        to="siren_web.scenarios",
                    ),
                ),
                (
                    "factor_type",
                    models.ForeignKey(
                        db_column="iddemandfactortype",
                        help_text="The type of demand factor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factor_instances",
                        to="siren_web.demandfactortype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Factor",
                "verbose_name_plural": "Demand Factors",
                "db_table": "demandfactor",
                "ordering": [
                    "scenario",
                    "factor_type__display_order",
                    "factor_type__name",
                ],
                "unique_together": {("scenario", "factor_type")},
            },
        ),
    ]
