# Generated by Django 5.2.7 on 2025-12-22 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0136_demandfactortype_demandprojectionscenario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("quarterly", "Quarterly Report"),
                            ("annual", "Annual Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        blank=True,
                        help_text="Required for quarterly reports",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        help_text="PDF file of the published report",
                        upload_to="published_reports/",
                    ),
                ),
                (
                    "published_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Stored separately in case user is deleted",
                        max_length=100,
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-quarter", "-published_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "year", "quarter"],
                        name="siren_web_p_report__a36dc9_idx",
                    ),
                    models.Index(
                        fields=["report_type", "year"],
                        name="siren_web_p_report__2c5c48_idx",
                    ),
                ],
                "unique_together": {("report_type", "year", "quarter")},
            },
        ),
    ]
