# Generated by Django 5.2.7 on 2025-12-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0137_publishedreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedreport",
            name="html_file",
            field=models.FileField(
                blank=True,
                help_text="HTML file with interactive Plotly charts",
                null=True,
                upload_to="published_reports/",
            ),
        ),
        migrations.AddField(
            model_name="publishedreport",
            name="html_file_size",
            field=models.IntegerField(
                blank=True, help_text="HTML file size in bytes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="publishedreport",
            name="file_size",
            field=models.IntegerField(
                blank=True, help_text="PDF file size in bytes", null=True
            ),
        ),
    ]
