# Generated by Django 5.2.7 on 2026-01-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0138_publishedreport_html_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonteCarloSimulation",
            fields=[
                ("simulation_id", models.AutoField(primary_key=True, serialize=False)),
                ("run_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "num_iterations",
                    models.IntegerField(
                        default=100000, help_text="Number of Monte Carlo iterations"
                    ),
                ),
                (
                    "target_year",
                    models.IntegerField(default=2040, help_text="Year to project to"),
                ),
                (
                    "probability_profile",
                    models.CharField(
                        choices=[
                            ("optimistic", "Optimistic"),
                            ("balanced", "Balanced"),
                            ("conservative", "Conservative"),
                        ],
                        default="optimistic",
                        help_text="Commissioning probability profile",
                        max_length=20,
                    ),
                ),
                (
                    "mean_re_percentage",
                    models.FloatField(
                        help_text="Mean RE% across all iterations", null=True
                    ),
                ),
                (
                    "median_re_percentage",
                    models.FloatField(
                        help_text="Median RE% (50th percentile)", null=True
                    ),
                ),
                (
                    "p10_re_percentage",
                    models.FloatField(
                        help_text="P10 RE% (pessimistic - 10th percentile)", null=True
                    ),
                ),
                (
                    "p90_re_percentage",
                    models.FloatField(
                        help_text="P90 RE% (optimistic - 90th percentile)", null=True
                    ),
                ),
                (
                    "std_dev_re_percentage",
                    models.FloatField(help_text="Standard deviation of RE%", null=True),
                ),
                (
                    "probability_75_percent",
                    models.FloatField(
                        help_text="Probability of achieving 75% RE target", null=True
                    ),
                ),
                (
                    "probability_85_percent",
                    models.FloatField(
                        help_text="Probability of achieving 85% RE target", null=True
                    ),
                ),
                (
                    "execution_time_seconds",
                    models.FloatField(
                        help_text="Total execution time in seconds", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if failed", null=True
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system",
                        help_text="User or system that triggered run",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "target_scenario",
                    models.ForeignKey(
                        help_text="Scenario this simulation evaluates",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monte_carlo_runs",
                        to="siren_web.targetscenario",
                    ),
                ),
            ],
            options={
                "db_table": "monte_carlo_simulations",
                "ordering": ["-run_date"],
            },
        ),
        migrations.CreateModel(
            name="MonteCarloResult",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "re_percentage_distribution",
                    models.JSONField(
                        help_text="Histogram of RE% results: {bins: [...], counts: [...]}"
                    ),
                ),
                (
                    "percentiles",
                    models.JSONField(
                        help_text="Percentile values: {p1: X, p5: Y, p10: Z, ..., p99: W}"
                    ),
                ),
                ("mean_wind_generation_2040", models.FloatField(null=True)),
                ("mean_solar_generation_2040", models.FloatField(null=True)),
                ("mean_dpv_generation_2040", models.FloatField(null=True)),
                ("mean_biomass_generation_2040", models.FloatField(null=True)),
                ("mean_total_demand_2040", models.FloatField(null=True)),
                (
                    "variance_contribution",
                    models.JSONField(
                        blank=True,
                        help_text="Variance contribution by factor: {commissioning: 0.4, cf: 0.3, demand: 0.2, delay: 0.1}",
                        null=True,
                    ),
                ),
                (
                    "sample_iterations",
                    models.JSONField(
                        blank=True,
                        help_text="First 1000 iteration results for debugging",
                        null=True,
                    ),
                ),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_results",
                        to="siren_web.montecarlosimulation",
                    ),
                ),
            ],
            options={
                "db_table": "monte_carlo_results",
            },
        ),
        migrations.CreateModel(
            name="MonteCarloParameter",
            fields=[
                ("parameter_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "parameter_category",
                    models.CharField(
                        choices=[
                            ("commissioning_probability", "Commissioning Probability"),
                            ("delay_distribution", "Delay Distribution"),
                            ("capacity_factor", "Capacity Factor"),
                            ("demand_growth", "Demand Growth"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(
                        help_text="e.g., 'commissioned_probability', 'wind_cf_mean'",
                        max_length=100,
                    ),
                ),
                (
                    "parameter_value",
                    models.JSONField(
                        help_text="Parameter value (can be scalar, array, or object)"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Data source or methodology",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="siren_web.montecarlosimulation",
                    ),
                ),
            ],
            options={
                "db_table": "monte_carlo_parameters",
            },
        ),
        migrations.AddIndex(
            model_name="montecarlosimulation",
            index=models.Index(
                fields=["-run_date", "status"], name="monte_carlo_run_dat_156351_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="montecarlosimulation",
            index=models.Index(
                fields=["target_scenario", "-run_date"],
                name="monte_carlo_target__63baca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="montecarloparameter",
            index=models.Index(
                fields=["simulation", "parameter_category"],
                name="monte_carlo_simulat_aa2cc3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="montecarloparameter",
            unique_together={("simulation", "parameter_name")},
        ),
    ]
