# Generated by Django 5.2.7 on 2026-01-10 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0139_montecarlosimulation_montecarloresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetscenario",
            name="operational_demand",
            field=models.FloatField(
                blank=True, help_text="Operational demand (GWh)", null=True
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated SIREN scenario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_scenarios",
                to="siren_web.scenarios",
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="storage",
            field=models.FloatField(
                blank=True, help_text="Storage capacity (MWh)", null=True
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="underlying_demand",
            field=models.FloatField(
                blank=True, help_text="Underlying demand (GWh)", null=True
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="year",
            field=models.IntegerField(
                default=2040, help_text="Target year for this scenario"
            ),
        ),
    ]
