# Generated by Django 5.2.7 on 2026-01-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0140_targetscenario_operational_demand_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="targetscenario",
            options={"ordering": ["year", "scenario_type"]},
        ),
        migrations.AlterUniqueTogether(
            name="targetscenario",
            unique_together={("scenario_type", "year")},
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="biomass_generation",
            field=models.FloatField(default=0, help_text="Biomass generation (GWh)"),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="dpv_generation",
            field=models.FloatField(
                default=0, help_text="Distributed rooftop solar generation (GWh)"
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="gas_generation",
            field=models.FloatField(default=0, help_text="Gas generation (GWh)"),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="solar_generation",
            field=models.FloatField(
                default=0, help_text="Utility-scale solar generation (GWh)"
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="target_emissions_tonnes",
            field=models.FloatField(
                blank=True,
                help_text="Target or projected emissions (tonnes CO2-e)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="target_re_percentage",
            field=models.FloatField(
                default=0, help_text="Target or projected RE percentage for this year"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("major", "Major Target"),
                    ("interim", "Interim Target"),
                    ("ordinary", "Ordinary Year"),
                ],
                default="ordinary",
                help_text="Type of year: major target, interim milestone, or ordinary projection",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="targetscenario",
            name="wind_generation",
            field=models.FloatField(default=0, help_text="Wind generation (GWh)"),
        ),
        migrations.AlterField(
            model_name="targetscenario",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="targetscenario",
            name="probability_percentage",
            field=models.FloatField(
                blank=True,
                help_text="Monte Carlo probability of achieving this scenario (%)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="targetscenario",
            name="scenario_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="targetscenario",
            name="year",
            field=models.IntegerField(
                db_index=True, help_text="Target or projection year"
            ),
        ),
        migrations.AddIndex(
            model_name="targetscenario",
            index=models.Index(
                fields=["year", "target_type"], name="target_scen_year_a932ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="targetscenario",
            index=models.Index(
                fields=["scenario_type", "year"], name="target_scen_scenari_e03e2d_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="biomass_generation_2040",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="dpv_generation_2040",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="gas_generation_2040",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="projected_emissions_2040_tonnes",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="projected_re_percentage_2040",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="solar_generation_2040",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="wind_generation_2040",
        ),
    ]
