# Generated by Django 5.2.7 on 2026-01-12 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0142_migrate_renewable_energy_targets"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RenewableEnergyTarget",
        ),
        migrations.RemoveField(
            model_name="targetscenario",
            name="scenario_name",
        ),
    ]
