# Generated by Django 5.2.7 on 2026-01-19 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0144_facility_lifecycle_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoadAnalysisSummary",
        ),
    ]
