# Generated by Django 5.2.7 on 2026-01-20 07:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0145_delete_loadanalysissummary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class for UI display",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#6c757d", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Risk Category",
                "verbose_name_plural": "Risk Categories",
                "db_table": "risk_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RiskScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short identifier for charts",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "wind_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Wind generation percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "solar_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Solar PV generation percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "storage_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Battery/storage percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "gas_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Gas generation percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "coal_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Coal generation percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "hydro_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Pumped hydro storage percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "hydrogen_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Green hydrogen percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "nuclear_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Nuclear generation percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "biomass_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Biomass generation percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "other_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Other generation percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("target_year", models.IntegerField(default=2040)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_baseline",
                    models.BooleanField(
                        default=False, help_text="Is this the baseline/BAU scenario?"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_risk_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_scenario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Associated generation scenario for capacity/mix data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_scenarios",
                        to="siren_web.targetscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Scenario",
                "verbose_name_plural": "Risk Scenarios",
                "db_table": "risk_scenarios",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_title", models.CharField(max_length=200)),
                (
                    "risk_description",
                    models.TextField(help_text="Detailed description of the risk"),
                ),
                (
                    "risk_cause",
                    models.TextField(blank=True, help_text="What causes this risk"),
                ),
                (
                    "risk_source",
                    models.CharField(
                        blank=True,
                        help_text="Technology or factor causing this risk (e.g., 'Wind turbines', 'Gas supply')",
                        max_length=100,
                    ),
                ),
                (
                    "inherent_likelihood",
                    models.IntegerField(
                        choices=[
                            (1, "Remote - Once every 10,000 to 100,000 years"),
                            (2, "Highly Unlikely - Once every 1,000 to 10,000 years"),
                            (3, "Unlikely - Once every 100 to 1,000 years"),
                            (4, "Possible - Once every 10 to 100 years"),
                            (5, "Quite Likely - Once every 1 to 10 years"),
                            (6, "Likely - More than once a year"),
                        ],
                        help_text="Likelihood before mitigations (1-6)",
                    ),
                ),
                (
                    "inherent_consequence",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Slight - Minor injury, >A$100K, localised temporary impact",
                            ),
                            (
                                2,
                                "Minor - Lost work case, A$100K-A$1M, localised short-term impact",
                            ),
                            (
                                3,
                                "Moderate - Partial disability, A$1-10M, medium scale years impact",
                            ),
                            (
                                4,
                                "Major - 1-20 fatalities, A$10-100M, medium scale decades impact",
                            ),
                            (
                                5,
                                "Massive - 20-200 fatalities, A$100M-1B, large scale decades impact",
                            ),
                            (
                                6,
                                "Catastrophic - >200 fatalities, >A$1B, regional permanent impact",
                            ),
                        ],
                        help_text="Consequence severity before mitigations (1-6)",
                    ),
                ),
                (
                    "inherent_consequence_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of consequences if risk occurs",
                    ),
                ),
                (
                    "inherent_likelihood_description",
                    models.TextField(
                        blank=True, help_text="Basis for likelihood assessment"
                    ),
                ),
                (
                    "mitigation_strategies",
                    models.TextField(
                        blank=True,
                        help_text="Strategies to reduce risk likelihood or consequence",
                    ),
                ),
                (
                    "residual_likelihood",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Remote - Once every 10,000 to 100,000 years"),
                            (2, "Highly Unlikely - Once every 1,000 to 10,000 years"),
                            (3, "Unlikely - Once every 100 to 1,000 years"),
                            (4, "Possible - Once every 10 to 100 years"),
                            (5, "Quite Likely - Once every 1 to 10 years"),
                            (6, "Likely - More than once a year"),
                        ],
                        help_text="Likelihood after mitigations (1-6)",
                        null=True,
                    ),
                ),
                (
                    "residual_consequence",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (
                                1,
                                "Slight - Minor injury, >A$100K, localised temporary impact",
                            ),
                            (
                                2,
                                "Minor - Lost work case, A$100K-A$1M, localised short-term impact",
                            ),
                            (
                                3,
                                "Moderate - Partial disability, A$1-10M, medium scale years impact",
                            ),
                            (
                                4,
                                "Major - 1-20 fatalities, A$10-100M, medium scale decades impact",
                            ),
                            (
                                5,
                                "Massive - 20-200 fatalities, A$100M-1B, large scale decades impact",
                            ),
                            (
                                6,
                                "Catastrophic - >200 fatalities, >A$1B, regional permanent impact",
                            ),
                        ],
                        help_text="Consequence severity after mitigations (1-6)",
                        null=True,
                    ),
                ),
                (
                    "assumptions",
                    models.TextField(
                        blank=True,
                        help_text="Key assumptions underlying this assessment",
                    ),
                ),
                (
                    "data_sources",
                    models.TextField(
                        blank=True, help_text="References and data sources"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Additional notes and comments"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True, help_text="Next review date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_events",
                        to="siren_web.riskcategory",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_events",
                        to="siren_web.riskscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Event",
                "verbose_name_plural": "Risk Events",
                "db_table": "risk_events",
                "ordering": [
                    "category",
                    "-inherent_likelihood",
                    "-inherent_consequence",
                ],
            },
        ),
    ]
