# Generated by Django 5.2.7 on 2026-01-21 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0146_riskcategory_riskscenario_riskevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskevent",
            name="scenario",
            field=models.ForeignKey(
                db_column="idscenarios",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_events",
                to="siren_web.scenarios",
            ),
        ),
    ]
