# Generated by Django 5.2.7 on 2026-02-07 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0147_alter_riskevent_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandfactor",
            name="steepness",
            field=models.FloatField(
                default=0.5,
                help_text="Steepness of S-curve transition (higher = sharper). Only used with S-curve growth type.",
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
