# Generated by Django 5.2.7 on 2026-02-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0149_monthlyreperformance_hydro_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreperformance",
            name="peak_instantaneous_re_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Date/time of peak instantaneous RE%", null=True
            ),
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="peak_instantaneous_re_percentage",
            field=models.FloatField(
                blank=True,
                help_text="Peak instantaneous RE% in any single trading interval",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreperformance",
            name="storage_charge",
            field=models.FloatField(default=0, help_text="Battery charging in GWh"),
        ),
        migrations.AlterField(
            model_name="monthlyreperformance",
            name="storage_discharge",
            field=models.FloatField(default=0, help_text="Battery discharge in GWh"),
        ),
    ]
