# Generated by Django 5.2.7 on 2026-02-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0150_add_peak_instantaneous_re"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPeakRE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True, unique=True)),
                (
                    "peak_re_percentage",
                    models.FloatField(
                        help_text="Peak 5-minute instantaneous operational RE%"
                    ),
                ),
                (
                    "peak_re_datetime",
                    models.DateTimeField(
                        help_text="DateTime of peak 5-minute RE% interval"
                    ),
                ),
                (
                    "re_generation_mw",
                    models.FloatField(
                        help_text="Total RE generation (MW) at peak interval"
                    ),
                ),
                (
                    "total_generation_mw",
                    models.FloatField(
                        help_text="Total operational generation (MW) at peak interval"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_peak_re",
                "ordering": ["-trading_date"],
            },
        ),
    ]
