# Generated by Django 5.2.7 on 2026-03-04 00:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0151_add_daily_peak_re"),
    ]

    operations = [
        migrations.CreateModel(
            name="CELProgram",
            fields=[
                ("cel_program_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Clean Energy Link – North'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short identifier, e.g. 'CEL-N'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cel_program",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="demandfactortype",
            name="category",
            field=models.CharField(
                choices=[
                    ("operational", "Operational Consumption Only"),
                    ("underlying", "Underlying Consumption Only"),
                    ("both", "Both Operational and Underlying"),
                ],
                default="both",
                help_text="Which demand type this factor applies to",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CELStage",
            fields=[
                ("cel_stage_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "stage_number",
                    models.IntegerField(
                        help_text="Stage order within the program (1, 2, 3 …)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'CEL-North – Malaga to Three Springs'",
                        max_length=150,
                    ),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("corridor", "Transmission Corridor"),
                            ("substation", "Substation Upgrade"),
                            ("terminal", "New Terminal"),
                        ],
                        default="corridor",
                        help_text="Physical nature of this stage",
                        max_length=20,
                    ),
                ),
                (
                    "funding_status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("environmental_approval", "Environmental Approval"),
                            ("funded", "Funded"),
                            ("under_construction", "Under Construction"),
                            ("operational", "Operational"),
                        ],
                        default="planning",
                        max_length=30,
                    ),
                ),
                (
                    "funding_status_weight_override",
                    models.FloatField(
                        blank=True,
                        help_text="Override the default probability weight for this stage's funding status.  Leave blank to use the system default.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("expected_operational_date", models.DateField(blank=True, null=True)),
                ("actual_operational_date", models.DateField(blank=True, null=True)),
                (
                    "capacity_new_mw",
                    models.FloatField(
                        help_text="New generation capacity enabled by this stage (MW)"
                    ),
                ),
                (
                    "capacity_unlocked_existing_mw",
                    models.FloatField(
                        default=0.0,
                        help_text="Existing constrained capacity freed by this stage (MW)",
                    ),
                ),
                (
                    "reserved_capacity_mw",
                    models.FloatField(
                        default=0.0,
                        help_text="Capacity already allocated to committed projects (MW)",
                    ),
                ),
                (
                    "route_coordinates",
                    models.TextField(
                        blank=True,
                        help_text="JSON list of [lat, lon] pairs defining the stage route, e.g. [[-31.84, 115.89], [-29.54, 115.76]]",
                        null=True,
                    ),
                ),
                (
                    "alignment_radius_km",
                    models.FloatField(
                        default=50.0,
                        help_text="Facilities within this distance of the route are considered aligned with this stage (km)",
                    ),
                ),
                ("from_latitude", models.FloatField(blank=True, null=True)),
                ("from_longitude", models.FloatField(blank=True, null=True)),
                ("to_latitude", models.FloatField(blank=True, null=True)),
                ("to_longitude", models.FloatField(blank=True, null=True)),
                ("served_region", models.CharField(blank=True, max_length=100)),
                (
                    "display_color",
                    models.CharField(
                        default="#FF6B35",
                        help_text="Hex colour for map rendering, e.g. '#FF6B35'",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cel_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="siren_web.celprogram",
                    ),
                ),
                (
                    "from_terminal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cel_from_stages",
                        to="siren_web.terminals",
                    ),
                ),
                (
                    "to_terminal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cel_to_stages",
                        to="siren_web.terminals",
                    ),
                ),
            ],
            options={
                "db_table": "cel_stage",
                "ordering": ["cel_program", "stage_number"],
                "unique_together": {("cel_program", "stage_number")},
            },
        ),
        migrations.CreateModel(
            name="FacilityCELAlignment",
            fields=[
                (
                    "idfacilitycelal",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "distance_to_route_km",
                    models.FloatField(
                        blank=True,
                        help_text="Distance from facility to the nearest point on the CEL stage route (km)",
                        null=True,
                    ),
                ),
                ("is_aligned", models.BooleanField(default=False)),
                (
                    "viability_score",
                    models.FloatField(
                        blank=True,
                        help_text="Combined viability score (0–1): cel_funding_weight × facility_status_weight × capacity_feasibility_score",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "cel_funding_weight",
                    models.FloatField(
                        blank=True,
                        help_text="CEL stage funding probability used in this score",
                        null=True,
                    ),
                ),
                (
                    "facility_status_weight",
                    models.FloatField(
                        blank=True,
                        help_text="Facility development status probability used in this score",
                        null=True,
                    ),
                ),
                (
                    "capacity_feasibility_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score reflecting whether CEL stage capacity covers this facility",
                        null=True,
                    ),
                ),
                (
                    "is_exception",
                    models.BooleanField(
                        default=False,
                        help_text="Flag facilities that bypass standard transmission constraint logic",
                    ),
                ),
                (
                    "exception_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("collocated_load", "Co-located Load/Generation"),
                            ("behind_meter", "Behind-the-Meter Large Project"),
                            ("goldfields_network", "Goldfields Regional Network"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this alignment record was computed",
                    ),
                ),
                (
                    "cel_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_alignments",
                        to="siren_web.celstage",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cel_alignments",
                        to="siren_web.facilities",
                    ),
                ),
            ],
            options={
                "db_table": "facility_cel_alignment",
                "ordering": ["-viability_score"],
                "unique_together": {("facility", "cel_stage")},
            },
        ),
    ]
