# Generated by Django 5.2.7 on 2026-03-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "siren_web",
            "0152_celprogram_alter_demandfactortype_category_celstage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CELStageGridLine",
            fields=[
                (
                    "idcel_stage_gridline",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "capacity_mw",
                    models.FloatField(
                        help_text="Capacity this line will carry for this CEL stage (MW)"
                    ),
                ),
                (
                    "line_role",
                    models.CharField(
                        choices=[
                            ("new", "New Construction"),
                            ("upgrade", "Capacity Upgrade"),
                        ],
                        default="new",
                        help_text="Whether this line is newly built or an upgrade of existing infrastructure",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cel_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_gridlines",
                        to="siren_web.celstage",
                    ),
                ),
                (
                    "grid_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cel_stage_associations",
                        to="siren_web.gridlines",
                    ),
                ),
            ],
            options={
                "db_table": "cel_stage_gridline",
                "ordering": ["line_role", "grid_line__line_name"],
                "unique_together": {("cel_stage", "grid_line")},
            },
        ),
        migrations.CreateModel(
            name="CELStageTerminal",
            fields=[
                (
                    "idcel_stage_terminal",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "capacity_mw",
                    models.FloatField(
                        help_text="Capacity this terminal will handle for this CEL stage (MW)"
                    ),
                ),
                (
                    "terminal_role",
                    models.CharField(
                        choices=[
                            ("new", "New Terminal"),
                            ("upgrade", "Capacity Upgrade"),
                        ],
                        default="new",
                        help_text="Whether this terminal is newly built or an upgrade of existing infrastructure",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cel_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_terminals",
                        to="siren_web.celstage",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cel_stage_associations",
                        to="siren_web.terminals",
                    ),
                ),
            ],
            options={
                "db_table": "cel_stage_terminal",
                "ordering": ["terminal_role", "terminal__terminal_name"],
                "unique_together": {("cel_stage", "terminal")},
            },
        ),
    ]
