# Generated by Django 5.2.7 on 2026-03-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0155_cel_start_date_remove_geo_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genetics",
        ),
        migrations.AlterModelOptions(
            name="celprogram",
            options={"ordering": ["start_date", "name"]},
        ),
        migrations.AlterModelOptions(
            name="celstage",
            options={"ordering": ["start_date", "stage_number"]},
        ),
        migrations.AlterField(
            model_name="gridlines",
            name="commissioning_date",
            field=models.DateField(
                blank=True, help_text="Actual or expected commissioning date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gridlines",
            name="decommissioning_date",
            field=models.DateField(
                blank=True,
                help_text="Actual or expected decommissioning date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="terminals",
            name="commissioning_date",
            field=models.DateField(
                blank=True, help_text="Actual or expected commissioning date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="terminals",
            name="decommissioning_date",
            field=models.DateField(
                blank=True,
                help_text="Actual or expected decommissioning date",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Optimisations",
        ),
    ]
