# Generated by Django 5.2.7 on 2026-03-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0156_delete_genetics_alter_celprogram_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridlines",
            name="emergency_capacity_mva",
            field=models.FloatField(
                blank=True, help_text="Emergency capacity in MVA", null=True
            ),
        ),
        migrations.AddField(
            model_name="gridlines",
            name="thermal_capacity_mva",
            field=models.FloatField(
                blank=True, help_text="Thermal capacity in MVA", null=True
            ),
        ),
    ]
