# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0157_gridlines_capacity_mva"),
    ]

    operations = [
        migrations.AddField(
            model_name="zones",
            name="kml_data",
            field=models.TextField(
                blank=True, null=True, help_text="KML Placemark data for this zone"
            ),
        ),
    ]
