# Generated by Django 5.2.7 on 2026-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0158_zones_kml_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gridlines",
            name="thermal_capacity_mw",
            field=models.FloatField(
                blank=True, help_text="Thermal capacity in MW", null=True
            ),
        ),
    ]
