# Generated by Django 5.2.7 on 2026-04-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0159_gridlines_thermal_capacity_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Django model name (e.g. 'Scenarios', 'FacilityScada')",
                        max_length=100,
                    ),
                ),
                (
                    "attribute_name",
                    models.CharField(
                        help_text="Model field or attribute name (e.g. 'capacity', 'quantity')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="How this reference provides data for this attribute",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="siren_web.reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Attribute",
                "verbose_name_plural": "Reference Attributes",
                "db_table": "ReferenceAttribute",
                "ordering": ["model_name", "attribute_name"],
                "unique_together": {("reference", "model_name", "attribute_name")},
            },
        ),
    ]
