# Generated by Django 5.2.7 on 2026-04-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0160_referenceattribute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyreperformance",
            name="emissions_intensity_kg_mwh",
        ),
        migrations.AddField(
            model_name="monthlyreperformance",
            name="emissions_intensity_kg_kwh",
            field=models.FloatField(
                default=0, help_text="Grid emissions intensity kg CO2-e/kWh"
            ),
            preserve_default=False,
        ),
    ]
