# Generated by Django 5.2.7 on 2026-08-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0164_facilitywindturbines_idwindturbines_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsooMethodVersion",
            fields=[
                (
                    "idesoomethodversion",
                    models.AutoField(
                        db_column="idesoomethodversion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_label", models.CharField(max_length=100, unique=True)),
                (
                    "effective_from_vintage",
                    models.PositiveIntegerField(
                        help_text="First ESOO publication year this method version applies from"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_breaking_change",
                    models.BooleanField(
                        default=False,
                        help_text="Whether G2 bias analysis should segment/annotate at this version",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESOO Method Version",
                "verbose_name_plural": "ESOO Method Versions",
                "db_table": "esoo_method_version",
                "ordering": ["effective_from_vintage"],
            },
        ),
        migrations.AlterField(
            model_name="facilities",
            name="developer_strength",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Unknown"),
                    ("weak", "Weak"),
                    ("smaller player", "Smaller Player"),
                    ("moderate", "Moderate"),
                    ("strong", "Strong"),
                    ("state backed", "State-backed"),
                    ("very_strong", "Very Strong"),
                ],
                default="moderate",
                help_text="Developer's assessed financial strength and track record",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="epc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Not Started"),
                    ("progressing", "Progressing"),
                    ("unclear", "Unclear"),
                    ("likely", "Likely"),
                    ("not locked", "Not Locked"),
                    ("locked", "Locked"),
                ],
                default="none",
                help_text="EPC contract status: not started, in negotiation, or locked",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="revenue_stack",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant", "Merchant"),
                    ("cis_merchant", "CIS + Merchant"),
                    ("ppa_cis", "PPA + CIS"),
                    ("ppa", "PPA"),
                    ("capacity", "Capacity-style"),
                    ("portfolio backed", "Portfolio Backed"),
                    ("strong", "Strong"),
                ],
                default="merchant",
                help_text="Revenue certainty classification",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AnnualDemandActual",
            fields=[
                (
                    "idannualdemandactual",
                    models.AutoField(
                        db_column="idannualdemandactual",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "demand_basis",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("underlying", "Underlying"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("annual_energy_gwh", models.FloatField(blank=True, null=True)),
                ("peak_demand_mw", models.FloatField(blank=True, null=True)),
                ("peak_datetime", models.DateTimeField(blank=True, null=True)),
                ("minimum_demand_mw", models.FloatField(blank=True, null=True)),
                ("minimum_datetime", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Annual Demand Actual",
                "verbose_name_plural": "Annual Demand Actuals",
                "db_table": "annual_demand_actual",
                "ordering": ["year"],
                "unique_together": {("year", "demand_basis")},
            },
        ),
        migrations.CreateModel(
            name="EsooVintage",
            fields=[
                (
                    "idesoovintage",
                    models.AutoField(
                        db_column="idesoovintage", primary_key=True, serialize=False
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="ESOO publication year, e.g. 2024", unique=True
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("modern_comparable", "Modern comparable (AEMO era)"),
                            ("heritage", "Heritage (IMO era)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hex digest of the retrieved source document",
                        max_length=64,
                    ),
                ),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path (relative to ESOO_ARCHIVE_DIR) of the retrieved document",
                        max_length=500,
                    ),
                ),
                (
                    "ingestion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("retrieved", "Retrieved"),
                            ("validated", "Validated"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vintages",
                        to="siren_web.esoomethodversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESOO Vintage",
                "verbose_name_plural": "ESOO Vintages",
                "db_table": "esoo_vintage",
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="EsooTaxonomyMapping",
            fields=[
                (
                    "idesootaxonomymapping",
                    models.AutoField(
                        db_column="idesootaxonomymapping",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "native_label",
                    models.CharField(
                        help_text="The vintage's own scenario label, e.g. 'high customer response'",
                        max_length=200,
                    ),
                ),
                (
                    "mapped_scenario",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("expected", "Expected"),
                            ("high", "High"),
                            ("not_applicable", "Not applicable"),
                            ("non_mappable", "Non-mappable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Rationale for the mapping decision"
                    ),
                ),
                (
                    "vintage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_mappings",
                        to="siren_web.esoovintage",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESOO Taxonomy Mapping",
                "verbose_name_plural": "ESOO Taxonomy Mappings",
                "db_table": "esoo_taxonomy_mapping",
                "unique_together": {("vintage", "native_label")},
            },
        ),
        migrations.CreateModel(
            name="EsooFigure",
            fields=[
                (
                    "idesoofigure",
                    models.AutoField(
                        db_column="idesoofigure", primary_key=True, serialize=False
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("demand", "Demand"),
                            (
                                "supply_adequacy",
                                "Supply adequacy (reference only, not a Powermatch input)",
                            ),
                        ],
                        default="demand",
                        max_length=20,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("energy", "Annual energy"),
                            ("peak", "Peak demand"),
                            ("minimum", "Minimum demand"),
                            ("rct", "Reserve Capacity Target"),
                            ("eue", "Expected Unserved Energy"),
                            ("capacity_outlook", "Capacity outlook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forecast_year",
                    models.PositiveIntegerField(help_text="Year this figure forecasts"),
                ),
                (
                    "demand_growth_scenario",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("expected", "Expected"),
                            ("high", "High"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="not_applicable",
                        help_text="Low/Expected/High — distinct from the project 'Scenarios' model",
                        max_length=20,
                    ),
                ),
                (
                    "poe_level",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(10, "POE10"), (50, "POE50"), (90, "POE90")],
                        help_text="10/50/90, or null where not applicable (e.g. energy)",
                        null=True,
                    ),
                ),
                (
                    "demand_basis",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("underlying", "Underlying"),
                            ("other", "Other"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        help_text="GWh for energy, MW for peak/minimum", max_length=10
                    ),
                ),
                ("source_document", models.CharField(blank=True, max_length=255)),
                (
                    "source_version",
                    models.CharField(
                        blank=True,
                        help_text="Published version/revision of the source",
                        max_length=100,
                    ),
                ),
                ("table_ref", models.CharField(blank=True, max_length=100)),
                ("page_ref", models.CharField(blank=True, max_length=50)),
                ("cell_ref", models.CharField(blank=True, max_length=100)),
                ("extraction_date", models.DateField(blank=True, null=True)),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("structured", "Structured source"),
                            ("pdf", "PDF fallback"),
                        ],
                        default="structured",
                        max_length=20,
                    ),
                ),
                (
                    "reconciliation_adjustment",
                    models.TextField(
                        blank=True,
                        help_text="Demand-definition crosswalk applied (FR-F07); blank if published operational figure used unadjusted",
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vintage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figures",
                        to="siren_web.esoovintage",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESOO Figure",
                "verbose_name_plural": "ESOO Figures",
                "db_table": "esoo_figure",
                "indexes": [
                    models.Index(
                        fields=["vintage", "domain", "metric"],
                        name="esoo_figure_vintage_bbf4eb_idx",
                    ),
                    models.Index(
                        fields=["forecast_year"], name="esoo_figure_forecas_dec993_idx"
                    ),
                    models.Index(
                        fields=["validation_status"],
                        name="esoo_figure_validat_d85bac_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "vintage",
                        "domain",
                        "metric",
                        "forecast_year",
                        "demand_growth_scenario",
                        "poe_level",
                        "demand_basis",
                    )
                },
            },
        ),
    ]
