# Generated by Django 5.2.7 on 2026-08-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0165_esoomethodversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esoofigure",
            name="metric",
            field=models.CharField(
                choices=[
                    ("energy", "Annual energy"),
                    ("peak_summer", "Peak demand (summer)"),
                    ("peak_winter", "Peak demand (winter)"),
                    ("minimum", "Minimum demand"),
                    ("rct", "Reserve Capacity Target"),
                    ("eue", "Expected Unserved Energy"),
                    ("capacity_outlook", "Capacity outlook"),
                ],
                max_length=20,
            ),
        ),
    ]
