# Generated by Django 5.2.7 on 2026-08-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0166_alter_esoofigure_metric"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsooSourceDocument",
            fields=[
                (
                    "idesoosourcedocument",
                    models.AutoField(
                        db_column="idesoosourcedocument",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("report", "Main ESOO report (PDF)"),
                            ("data_register", "Data Register workbook (XLSX)"),
                            ("demand_traces", "Demand Traces workbook (XLSB)"),
                            (
                                "reliability_methodology",
                                "EY Reliability Assessment Methodology report",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path (relative to ESOO_ARCHIVE_DIR) of the retrieved document",
                        max_length=500,
                    ),
                ),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vintage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_documents",
                        to="siren_web.esoovintage",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESOO Source Document",
                "verbose_name_plural": "ESOO Source Documents",
                "db_table": "esoo_source_document",
                "unique_together": {("vintage", "doc_type")},
            },
        ),
    ]
