# Generated by Django 5.2.7 on 2026-08-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0167_esoosourcedocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esoosourcedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("report", "Main ESOO report (PDF)"),
                    (
                        "data_register",
                        'Data Register workbook (XLSX) — or its "Figures" half, in years AEMO split it',
                    ),
                    (
                        "data_register_tables",
                        'Data Register "Tables" workbook (XLSX) — years where AEMO split the register in two',
                    ),
                    ("demand_traces", "Demand Traces workbook (XLSB)"),
                    (
                        "reliability_methodology",
                        "EY Reliability Assessment Methodology report",
                    ),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
