# Generated by Django 5.2.7 on 2026-08-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0168_alter_esoosourcedocument_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarios",
            name="interval_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Dispatch time-step length in minutes for this scenario's supplyfactors data (e.g. 60 for hourly, 30 for half-hourly). Purely additive: every scenario created before this field existed keeps its implicit hourly behaviour via the default of 60.",
            ),
        ),
    ]
