# Generated by Django 5.2.7 on 2026-08-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0169_scenarios_interval_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvVintage",
            fields=[
                (
                    "idevvintage",
                    models.AutoField(
                        db_column="idevvintage", primary_key=True, serialize=False
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="CSIRO EV Projections release identifier, e.g. '2024-Q3'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("licence", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hex digest of the retrieved source document",
                        max_length=64,
                    ),
                ),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path (relative to EV_ARCHIVE_DIR) of the retrieved document",
                        max_length=500,
                    ),
                ),
                (
                    "ingestion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("retrieved", "Retrieved"),
                            ("validated", "Validated"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "EV Vintage",
                "verbose_name_plural": "EV Vintages",
                "db_table": "ev_vintage",
                "ordering": ["-release_date", "version"],
            },
        ),
        migrations.CreateModel(
            name="V2gInterfaceStub",
            fields=[
                (
                    "idv2ginterfacestub",
                    models.AutoField(
                        db_column="idv2ginterfacestub",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "csiro_scenario",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "v2g_capable_fraction",
                    models.FloatField(
                        default=0.0,
                        help_text="Fraction of the fleet assumed V2G-capable; dormant",
                    ),
                ),
                (
                    "availability_profile_slot",
                    models.CharField(
                        blank=True,
                        help_text="Dormant placeholder describing when a V2G-capable vehicle is assumed plugged in/available",
                        max_length=100,
                    ),
                ),
                (
                    "exportable_capacity_kw",
                    models.FloatField(
                        default=0.0,
                        help_text="Dormant; no dispatch logic reads this yet",
                    ),
                ),
                (
                    "round_trip_efficiency",
                    models.FloatField(
                        default=0.0,
                        help_text="Dormant; no dispatch logic reads this yet",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="Phase 2 dormant schema only — FR-17. No V2G dispatch runs this Sprint (O9).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "V2G Interface Stub",
                "verbose_name_plural": "V2G Interface Stubs",
                "db_table": "v2g_interface_stub",
            },
        ),
        migrations.CreateModel(
            name="EvActualsRecord",
            fields=[
                (
                    "idevactualsrecord",
                    models.AutoField(
                        db_column="idevactualsrecord", primary_key=True, serialize=False
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "region",
                    models.CharField(
                        default="WA",
                        help_text="State-level unless/until a finer resolution is confirmed (O4)",
                        max_length=100,
                    ),
                ),
                ("fleet_count", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dot_wa_registrations", "DoT WA vehicle registrations"),
                            ("abs_motor_vehicle_census", "ABS Motor Vehicle Census"),
                            ("ev_council_fcai", "EV Council / FCAI sales index"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resolution_ceiling",
                    models.CharField(
                        blank=True,
                        help_text="Finest geography this source actually supports, e.g. 'state total' (O4)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "EV Actuals Record",
                "verbose_name_plural": "EV Actuals Records",
                "db_table": "ev_actuals_record",
                "ordering": ["year"],
                "unique_together": {("year", "region", "source")},
            },
        ),
        migrations.CreateModel(
            name="EvLoadTrace",
            fields=[
                (
                    "idevloadtrace",
                    models.AutoField(
                        db_column="idevloadtrace", primary_key=True, serialize=False
                    ),
                ),
                (
                    "csiro_scenario",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "charging_mode",
                    models.CharField(
                        choices=[
                            (
                                "unmanaged",
                                "Unmanaged (plug-in-on-arrival) — honest baseline, D3",
                            ),
                            ("managed", "Managed (ToU redistribution lever), D3/D11"),
                        ],
                        default="unmanaged",
                        max_length=10,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path (relative to EV_TRACE_DIR) of the stored .npy half-hourly trace",
                        max_length=500,
                    ),
                ),
                ("n_intervals", models.PositiveIntegerField()),
                (
                    "annual_energy_mwh",
                    models.FloatField(
                        help_text="Source annual energy anchor; FR-09 requires the trace's integral to match this to <= 0.01%"
                    ),
                ),
                (
                    "integral_check_pct",
                    models.FloatField(
                        blank=True,
                        help_text="Achieved |integral - annual_energy_mwh| / annual_energy_mwh * 100 at build time (FR-09 near-exact check)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "EV Load Trace",
                "verbose_name_plural": "EV Load Traces",
                "db_table": "ev_load_trace",
                "unique_together": {("csiro_scenario", "year", "charging_mode")},
            },
        ),
        migrations.CreateModel(
            name="EvSourceDocument",
            fields=[
                (
                    "idevsourcedocument",
                    models.AutoField(
                        db_column="idevsourcedocument",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("csiro_report", "CSIRO EV Projections report"),
                            (
                                "aemo_isp_step_change",
                                "AEMO ISP Step Change charging-profile document",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path (relative to EV_ARCHIVE_DIR) of the retrieved document",
                        max_length=500,
                    ),
                ),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vintage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_documents",
                        to="siren_web.evvintage",
                    ),
                ),
            ],
            options={
                "verbose_name": "EV Source Document",
                "verbose_name_plural": "EV Source Documents",
                "db_table": "ev_source_document",
                "unique_together": {("vintage", "doc_type")},
            },
        ),
        migrations.CreateModel(
            name="SwisBoundaryMembership",
            fields=[
                (
                    "idswisboundarymembership",
                    models.AutoField(
                        db_column="idswisboundarymembership",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("postcode", models.CharField(max_length=10, unique=True)),
                (
                    "zone_name",
                    models.CharField(
                        blank=True,
                        help_text="Intermediate zone this postcode belongs to",
                        max_length=100,
                    ),
                ),
                (
                    "membership_status",
                    models.CharField(
                        choices=[
                            ("in", "In SWIS"),
                            ("out", "Out of SWIS (NWIS/off-grid)"),
                            ("partial", "Partial (edge postcode)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "apportionment_fraction",
                    models.FloatField(
                        default=1.0,
                        help_text="D9: reserved for edge-postcode apportionment; unused (always 1.0) this Sprint",
                    ),
                ),
                ("centroid_lat", models.FloatField(blank=True, null=True)),
                ("centroid_lon", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SWIS Boundary Membership",
                "verbose_name_plural": "SWIS Boundary Memberships",
                "db_table": "swis_boundary_membership",
                "indexes": [
                    models.Index(
                        fields=["membership_status"],
                        name="swis_bounda_members_58e578_idx",
                    ),
                    models.Index(
                        fields=["zone_name"], name="swis_bounda_zone_na_a4aa13_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvChargingProfile",
            fields=[
                (
                    "idevchargingprofile",
                    models.AutoField(
                        db_column="idevchargingprofile",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("public", "Public"),
                            ("commercial", "Commercial/fleet"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "share_of_charging",
                    models.FloatField(
                        help_text="Fraction of total charging energy at this location (D8: Step Change)"
                    ),
                ),
                (
                    "tou_responsiveness",
                    models.FloatField(
                        default=0.0,
                        help_text="0-1: how responsive this location's load is to a ToU/managed-charging lever (D3)",
                    ),
                ),
                (
                    "weekday_halfhourly_shape",
                    models.JSONField(
                        help_text="48 fractions (sum to 1) — relative charging energy per half-hour, weekday"
                    ),
                ),
                (
                    "weekend_halfhourly_shape",
                    models.JSONField(
                        help_text="48 fractions (sum to 1) — relative charging energy per half-hour, weekend"
                    ),
                ),
                ("report_citation", models.CharField(blank=True, max_length=255)),
                ("page_ref", models.CharField(blank=True, max_length=50)),
                ("table_ref", models.CharField(blank=True, max_length=100)),
                ("citation_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charging_profiles",
                        to="siren_web.evsourcedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "EV Charging Profile",
                "verbose_name_plural": "EV Charging Profiles",
                "db_table": "ev_charging_profile",
                "unique_together": {("source_document", "location")},
            },
        ),
        migrations.CreateModel(
            name="EvUptakePostcodeFigure",
            fields=[
                (
                    "idevuptakepostcodefigure",
                    models.AutoField(
                        db_column="idevuptakepostcodefigure",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        help_text="WA postcode, e.g. '6000'", max_length=10
                    ),
                ),
                (
                    "forecast_year",
                    models.PositiveIntegerField(
                        help_text="Year this figure forecasts (2021-2050 per FR-01)"
                    ),
                ),
                (
                    "csiro_scenario",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fleet_count",
                    models.FloatField(
                        blank=True,
                        help_text="D6: retained for context/tracking, not the primary driver",
                        null=True,
                    ),
                ),
                (
                    "consumption_kwh",
                    models.FloatField(
                        blank=True, help_text="D6: primary load driver", null=True
                    ),
                ),
                ("source_version", models.CharField(blank=True, max_length=100)),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("structured", "Structured source"),
                            ("pdf", "PDF fallback"),
                        ],
                        default="structured",
                        max_length=20,
                    ),
                ),
                ("extraction_date", models.DateField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vintage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postcode_figures",
                        to="siren_web.evvintage",
                    ),
                ),
            ],
            options={
                "verbose_name": "EV Uptake Postcode Figure",
                "verbose_name_plural": "EV Uptake Postcode Figures",
                "db_table": "ev_uptake_postcode_figure",
                "indexes": [
                    models.Index(
                        fields=["vintage", "csiro_scenario", "forecast_year"],
                        name="ev_uptake_p_vintage_f919af_idx",
                    ),
                    models.Index(
                        fields=["postcode"], name="ev_uptake_p_postcod_103995_idx"
                    ),
                    models.Index(
                        fields=["validation_status"],
                        name="ev_uptake_p_validat_3c2783_idx",
                    ),
                ],
                "unique_together": {
                    ("vintage", "postcode", "forecast_year", "csiro_scenario")
                },
            },
        ),
        migrations.CreateModel(
            name="EvSuppressionFlag",
            fields=[
                (
                    "idevsuppressionflag",
                    models.AutoField(
                        db_column="idevsuppressionflag",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("postcode", models.CharField(max_length=10)),
                ("forecast_year", models.PositiveIntegerField()),
                (
                    "csiro_scenario",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (
                                "suppressed_by_source",
                                "Suppressed by CSIRO's own privacy threshold",
                            ),
                            (
                                "unexplained",
                                "Unexplained (counts as pipeline data loss, FR-20)",
                            ),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "threshold_note",
                    models.CharField(
                        blank=True,
                        help_text="CSIRO's stated suppression threshold this row was matched against",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vintage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppression_flags",
                        to="siren_web.evvintage",
                    ),
                ),
            ],
            options={
                "verbose_name": "EV Suppression Flag",
                "verbose_name_plural": "EV Suppression Flags",
                "db_table": "ev_suppression_flag",
                "unique_together": {
                    ("vintage", "postcode", "forecast_year", "csiro_scenario")
                },
            },
        ),
    ]
