# Generated by Django 5.2.7 on 2026-08-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0171_ev_charging_profile_real_taxonomy"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="evsourcedocument",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="evsourcedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    (
                        "csiro_postcode_fleet_csv",
                        "CSIRO postcode-level fleet/consumption CSV (one per TECH_TYPE, real CSIRO Data Shop export)",
                    ),
                    (
                        "csiro_summary",
                        "CSIRO state-level summary CSV (WA_SUMMARY_*.csv, no postcode breakdown)",
                    ),
                    (
                        "csiro_report",
                        "CSIRO EV Projections report/methodology document",
                    ),
                    (
                        "aemo_isp_step_change",
                        "AEMO ISP Step Change charging-profile document",
                    ),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evsourcedocument",
            unique_together={("vintage", "doc_type", "local_file_path")},
        ),
    ]
