# Generated by Django 5.2.7 on 2026-08-30 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0173_swis_and_postcode_boundary"),
    ]

    operations = [
        migrations.AddField(
            model_name="evactualsrecord",
            name="bev_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evactualsrecord",
            name="period_end",
            field=models.DateField(
                blank=True,
                help_text="The quarter-end this annual snapshot was taken from",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evactualsrecord",
            name="phev_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EvActualsDocument",
            fields=[
                (
                    "idevactualsdocument",
                    models.AutoField(
                        db_column="idevactualsdocument",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dot_wa_registrations", "DoT WA vehicle registrations"),
                            ("abs_motor_vehicle_census", "ABS Motor Vehicle Census"),
                            ("ev_council_fcai", "EV Council / FCAI sales index"),
                        ],
                        default="dot_wa_registrations",
                        max_length=30,
                    ),
                ),
                (
                    "quarter_label",
                    models.CharField(help_text="e.g. 'Dec 2025'", max_length=20),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="Last day of the quarter this report covers"
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path (relative to EV_ARCHIVE_DIR) of the retrieved PDF",
                        max_length=500,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hex digest of the retrieved PDF",
                        max_length=64,
                    ),
                ),
                (
                    "report_prepared_date",
                    models.DateField(
                        blank=True,
                        help_text="'Prepared by DoT…' date printed in the report",
                        null=True,
                    ),
                ),
                (
                    "series_rows_extracted",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Figure 1b rows parsed from this PDF (0 for pre-2025 chart-only layouts)",
                    ),
                ),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "EV Actuals Document",
                "verbose_name_plural": "EV Actuals Documents",
                "db_table": "ev_actuals_document",
                "ordering": ["-period_end"],
                "unique_together": {("source", "period_end")},
            },
        ),
        migrations.AddField(
            model_name="evactualsrecord",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annual_records",
                to="siren_web.evactualsdocument",
            ),
        ),
        migrations.CreateModel(
            name="EvActualsQuarter",
            fields=[
                (
                    "idevactualsquarter",
                    models.AutoField(
                        db_column="idevactualsquarter",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dot_wa_registrations", "DoT WA vehicle registrations"),
                            ("abs_motor_vehicle_census", "ABS Motor Vehicle Census"),
                            ("ev_council_fcai", "EV Council / FCAI sales index"),
                        ],
                        default="dot_wa_registrations",
                        max_length=30,
                    ),
                ),
                ("region", models.CharField(default="WA", max_length=100)),
                ("period_end", models.DateField(help_text="Last day of the quarter")),
                ("bev_count", models.FloatField(blank=True, null=True)),
                (
                    "phev_count",
                    models.FloatField(
                        blank=True,
                        help_text="FCEV is suppressed by DoT, so Total = BEV + PHEV",
                        null=True,
                    ),
                ),
                ("total_count", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Most recent report this figure was read from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarters",
                        to="siren_web.evactualsdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "EV Actuals Quarter",
                "verbose_name_plural": "EV Actuals Quarters",
                "db_table": "ev_actuals_quarter",
                "ordering": ["period_end"],
                "unique_together": {("source", "region", "period_end")},
            },
        ),
    ]
