# Generated by Django 5.2.7 on 2026-09-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0175_unify_source_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandRun",
            fields=[
                (
                    "idcommandrun",
                    models.AutoField(
                        db_column="idcommandrun", primary_key=True, serialize=False
                    ),
                ),
                (
                    "command_key",
                    models.CharField(
                        help_text="Key into powermatchui.pipeline_registry.PIPELINE_COMMANDS",
                        max_length=64,
                    ),
                ),
                ("management_command", models.CharField(max_length=64)),
                (
                    "args",
                    models.JSONField(
                        default=list,
                        help_text="Resolved argv actually passed to call_command",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("web", "Web UI"),
                            ("cron", "Cron"),
                            ("cli", "Manual CLI"),
                        ],
                        default="web",
                        max_length=8,
                    ),
                ),
                ("return_code", models.IntegerField(blank=True, null=True)),
                (
                    "output",
                    models.TextField(
                        blank=True, help_text="Combined stdout+stderr, tail-capped"
                    ),
                ),
                ("error_summary", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_command_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Command Run",
                "verbose_name_plural": "Pipeline Command Runs",
                "db_table": "pipeline_command_run",
                "ordering": ["-created_at"],
            },
        ),
    ]
