# Generated by Django 5.2.7 on 2026-09-13 08:04
# Split out of an autogenerated migration: this AlterField reflects a
# pre-existing, already-committed choices change on EsooFigure.extraction_method
# (the 'dpv_subtraction' choice) that had never been migrated -- unrelated to
# the EsooForecastAdjustment model added in 0178, kept separate on purpose.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0176_commandrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esoofigure",
            name="extraction_method",
            field=models.CharField(
                choices=[
                    ("structured", "Structured source"),
                    ("pdf", "PDF fallback"),
                    (
                        "dpv_subtraction",
                        "Derived: underlying minus DPV (FR-F07/D13 crosswalk)",
                    ),
                ],
                default="structured",
                max_length=20,
            ),
        ),
    ]
