# Generated by Django 5.2.7 on 2026-09-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0177_alter_esoofigure_extraction_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsooForecastAdjustment",
            fields=[
                (
                    "idesooforecastadjustment",
                    models.AutoField(
                        db_column="idesooforecastadjustment",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "growth_assumption",
                                "Growth assumption bias (residual mean error)",
                            ),
                            ("weather_normalization", "Weather normalisation"),
                            ("pv_recalibration", "Rooftop PV recalibration"),
                            ("block_load_removal", "Block-load delay removal"),
                            (
                                "industrial_load_survey",
                                "Industrial load survey correction",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "horizon",
                    models.IntegerField(
                        help_text="forecast_year - vintage.year, denormalised for querying"
                    ),
                ),
                ("original_value", models.FloatField()),
                (
                    "adjustment_value",
                    models.FloatField(
                        help_text="Signed correction; original_value + adjustment_value = adjusted_value"
                    ),
                ),
                ("adjusted_value", models.FloatField()),
                ("unit", models.CharField(max_length=10)),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("forecasts_run_high", "Forecasts run high"),
                            ("forecasts_run_low", "Forecasts run low"),
                            ("insufficient_evidence", "Insufficient evidence"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("p_value", models.FloatField(blank=True, null=True)),
                ("n", models.PositiveIntegerField(blank=True, null=True)),
                ("methodology_notes", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("computed", "Computed from bias analysis"),
                            ("manual", "Manually entered or overridden"),
                        ],
                        default="computed",
                        max_length=10,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_to_scenario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set once this adjustment was actually used to build a Powermatch scenario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="esoo_forecast_adjustments",
                        to="siren_web.scenarios",
                    ),
                ),
                (
                    "source_figure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="siren_web.esoofigure",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESOO Forecast Adjustment",
                "verbose_name_plural": "ESOO Forecast Adjustments",
                "db_table": "esoo_forecast_adjustment",
                "ordering": ["-computed_at"],
                "unique_together": {("source_figure", "category")},
            },
        ),
    ]
