# Generated by Django 5.2.7 on 2026-09-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0178_esoo_forecast_adjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityscada",
            name="quantity",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Half-hourly energy in MWh, despite the field name. To get average MW over the interval, multiply by 2. See compute_annual_demand_actuals.py module docstring.",
                max_digits=12,
            ),
        ),
    ]
