# Generated by Django 5.2.7 on 2026-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0179_alter_facilityscada_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyFactorMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                (
                    "facility_ids",
                    models.JSONField(
                        help_text="Ordered facility ids; row i of the matrix belongs to facility_ids[i]"
                    ),
                ),
                (
                    "n_hours",
                    models.PositiveIntegerField(
                        help_text="Columns in the matrix, e.g. 8760 for an hourly year"
                    ),
                ),
                ("dtype", models.CharField(default="float32", max_length=10)),
                (
                    "data",
                    models.BinaryField(
                        help_text="facility_ids x n_hours array, row-major, packed as `dtype`"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "supply_factor_matrix",
            },
        ),
    ]
