# Generated by Django 5.2.7 on 2026-09-14 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0180_supply_factor_matrix"),
    ]

    operations = [
        migrations.DeleteModel(
            name="supplyfactors",
        ),
    ]
