# Generated by Django 5.2.7 on 2026-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0181_drop_supplyfactors"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarios",
            name="reference_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="For an AEMO/ESOO-built demand scenario (see esoo_scenario_views.build_scenario_from_esoo): the real FacilityScada year whose chronological shape was used as the synthesis prior for this scenario's Load trace. Null for scenarios that aren't ESOO-built, or built before this field existed. Lets a consumer (e.g. powermapui's Run Power) use the same weather year the demand trace's own shape came from, rather than requiring a separate manual pick.",
                null=True,
            ),
        ),
    ]
