# Generated by Django 5.2.7 on 2026-09-15 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0182_scenarios_reference_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GencostCostFigure",
            fields=[
                (
                    "idgencostcostfigure",
                    models.AutoField(
                        db_column="idgencostcostfigure",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_technology_label", models.CharField(max_length=200)),
                (
                    "cost_case",
                    models.CharField(
                        choices=[
                            ("current_policies", "Current policies"),
                            ("global_nze_2050", "Global NZE by 2050"),
                            ("global_nze_post_2050", "Global NZE post 2050"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cost_component",
                    models.CharField(
                        choices=[
                            ("capex", "Capital cost ($/kW)"),
                            ("fom", "Fixed O&M"),
                            ("vom", "Variable O&M"),
                            ("fuel", "Fuel cost"),
                            ("lcoe", "LCOE"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "financial_year",
                    models.PositiveIntegerField(
                        help_text="Forecast year this figure applies to"
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("sheet_ref", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "GenCost Cost Figure",
                "verbose_name_plural": "GenCost Cost Figures",
                "db_table": "gencost_cost_figure",
            },
        ),
        migrations.CreateModel(
            name="GencostTechnologyMapping",
            fields=[
                (
                    "idgencosttechnologymapping",
                    models.AutoField(
                        db_column="idgencosttechnologymapping",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_technology_label", models.CharField(max_length=200, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GenCost Technology Mapping",
                "verbose_name_plural": "GenCost Technology Mappings",
                "db_table": "gencost_technology_mapping",
                "ordering": ["raw_technology_label"],
            },
        ),
        migrations.CreateModel(
            name="GencostVintage",
            fields=[
                (
                    "idgencostvintage",
                    models.AutoField(
                        db_column="idgencostvintage", primary_key=True, serialize=False
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        help_text="GenCost report edition, e.g. '2025-26'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GenCost Vintage",
                "verbose_name_plural": "GenCost Vintages",
                "db_table": "gencost_vintage",
                "ordering": ["-edition"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="sourcedocument",
            name="source_document_exactly_one_vintage",
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="dap_file_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="CSIRO Data Access Portal's stable per-file id, used to dedupe auto-fetched GenCost files",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("report", "ESOO — Main report (PDF)"),
                    (
                        "data_register",
                        'ESOO — Data Register workbook (XLSX) — or its "Figures" half, in years AEMO split it',
                    ),
                    (
                        "data_register_tables",
                        'ESOO — Data Register "Tables" workbook (XLSX) — years where AEMO split the register in two',
                    ),
                    ("demand_traces", "ESOO — Demand Traces workbook (XLSB)"),
                    (
                        "reliability_methodology",
                        "ESOO — EY Reliability Assessment Methodology report",
                    ),
                    (
                        "csiro_postcode_fleet_csv",
                        "EV — CSIRO postcode-level fleet/consumption CSV (one per TECH_TYPE, real CSIRO Data Shop export)",
                    ),
                    (
                        "csiro_summary",
                        "EV — CSIRO state-level summary CSV (WA_SUMMARY_*.csv, no postcode breakdown)",
                    ),
                    (
                        "csiro_report",
                        "EV — CSIRO EV Projections report/methodology document",
                    ),
                    (
                        "aemo_isp_step_change",
                        "EV — AEMO ISP Step Change charging-profile document",
                    ),
                    (
                        "gencost_workbook_consult",
                        "GenCost — Consultation draft Appendix Tables workbook (XLSX)",
                    ),
                    (
                        "gencost_workbook_final",
                        "GenCost — Final Appendix Tables workbook (XLSX)",
                    ),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="local_file_path",
            field=models.CharField(
                blank=True,
                help_text="Path (relative to ESOO_ARCHIVE_DIR / EV_ARCHIVE_DIR / GENCOST_ARCHIVE_DIR) of the retrieved document",
                max_length=500,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="technologyyears",
            unique_together={("idtechnologies", "year")},
        ),
        migrations.AddField(
            model_name="gencosttechnologymapping",
            name="technology",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to ignore this GenCost label (not applied to Technology Years)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gencost_mappings",
                to="siren_web.technologies",
            ),
        ),
        migrations.AddField(
            model_name="gencostvintage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gencost_vintages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gencostcostfigure",
            name="vintage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="figures",
                to="siren_web.gencostvintage",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="gencost_vintage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_documents",
                to="siren_web.gencostvintage",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("gencost_vintage", "doc_type"),
                name="uniq_gencost_source_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("esoo_vintage__isnull", False),
                        ("ev_vintage__isnull", True),
                        ("gencost_vintage__isnull", True),
                    ),
                    models.Q(
                        ("esoo_vintage__isnull", True),
                        ("ev_vintage__isnull", False),
                        ("gencost_vintage__isnull", True),
                    ),
                    models.Q(
                        ("esoo_vintage__isnull", True),
                        ("ev_vintage__isnull", True),
                        ("gencost_vintage__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="source_document_exactly_one_vintage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gencostcostfigure",
            unique_together={
                (
                    "vintage",
                    "raw_technology_label",
                    "cost_case",
                    "cost_component",
                    "financial_year",
                )
            },
        ),
    ]
