# Generated by Django 5.2.7 on 2026-09-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0183_gencostcostfigure_gencosttechnologymapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gencosttechnologymapping",
            name="ignored",
            field=models.BooleanField(
                default=False,
                help_text="Explicitly not applicable to this project -- won't block a cost case's Apply button, and won't be nagged about",
            ),
        ),
        migrations.AlterField(
            model_name="gencosttechnologymapping",
            name="technology",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank (and unignored) if still pending review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gencost_mappings",
                to="siren_web.technologies",
            ),
        ),
    ]
