# Generated by Django 5.2.7 on 2026-09-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0184_gencosttechnologymapping_ignored_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technologyyears",
            name="capex_premium_pct",
            field=models.FloatField(
                blank=True,
                help_text="Percent this row's capex was scaled by over its source figure, e.g. a WA cost premium applied on top of a GenCost national-average value (see apply_gencost_cost_case). Null means this row's provenance doesn't track a premium (manually entered, or predates this field).",
                null=True,
            ),
        ),
    ]
