# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0185_technologyyears_capex_premium_pct"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPVGenerationMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                (
                    "n_intervals",
                    models.PositiveIntegerField(
                        help_text="Half-hourly intervals in the year, e.g. 17520 (17568 in a leap year)"
                    ),
                ),
                ("dtype", models.CharField(default="float32", max_length=10)),
                (
                    "data",
                    models.BinaryField(
                        help_text="n_intervals array of estimated DPV generation (MW), packed as `dtype`"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dpv_generation_matrix",
            },
        ),
    ]
