# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0186_dpv_generation_matrix"),
    ]

    operations = [
        migrations.DeleteModel(name="DPVGeneration"),
    ]
