# Generated by Django 5.2.7 on 2026-09-19 07:31

from django.db import migrations, models


def set_distillate_fuel_type(apps, schema_editor):
    Technologies = apps.get_model("siren_web", "Technologies")
    Technologies.objects.filter(
        technology_name="Distillate", fuel_type__isnull=True
    ).update(fuel_type="DISTILLATE")


def clear_distillate_fuel_type(apps, schema_editor):
    Technologies = apps.get_model("siren_web", "Technologies")
    Technologies.objects.filter(
        technology_name="Distillate", fuel_type="DISTILLATE"
    ).update(fuel_type=None)


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0191_drop_wholesaleprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technologies",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WIND", "Wind"),
                    ("SOLAR", "Solar"),
                    ("GAS", "Gas"),
                    ("DISTILLATE", "Distillate"),
                    ("COAL", "Coal"),
                    ("HYDRO", "Hydro"),
                    ("BIOMASS", "Biomass"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.RunPython(set_distillate_fuel_type, clear_distillate_fuel_type),
    ]
