# Generated by Django 5.2.7 on 2026-09-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0192_technologies_distillate_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitywindturbines",
            name="assumed_turbine",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="Representative turbine chosen for SAM when no turbine model is specified (reference turbine, scaling and the inputs it was chosen from). Written by the simulation, never by hand.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="windturbines",
            name="is_reference",
            field=models.BooleanField(
                default=False,
                help_text="Reference/representative design rather than a specific commercial model",
            ),
        ),
        migrations.AddField(
            model_name="windturbines",
            name="power_curve_csv",
            field=models.CharField(
                blank=True,
                help_text="Slug of this turbine's curve in the CSV turbine library (TURBINE_LIBRARY_DIR/curves/<slug>.csv)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="windturbines",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Where the specification and power curve came from",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="windturbines",
            name="vintage_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Approximate year this turbine design became available",
                null=True,
            ),
        ),
    ]
