# Generated by Django 5.2.7 on 2026-09-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0194_esoofigure_demand_basis_delivered"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                (
                    "demand_ids",
                    models.JSONField(
                        help_text="Ordered demand ids; row i of the matrix belongs to demand_ids[i]"
                    ),
                ),
                (
                    "n_hours",
                    models.PositiveIntegerField(
                        help_text="Columns in the matrix, e.g. 17520 for a half-hourly year"
                    ),
                ),
                ("dtype", models.CharField(default="float32", max_length=10)),
                (
                    "data",
                    models.BinaryField(
                        help_text="demand_ids x n_hours array, row-major, packed as `dtype`"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "demand_matrix",
            },
        ),
        migrations.AddField(
            model_name="scenarios",
            name="weather_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Calendar year whose generation/storage facility traces this scenario dispatches against. Set explicitly when building/editing a scenario -- no longer inferred from an implicit Load facility (see the Demand model for grid demand, which is selected separately at dispatch run time).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                ("iddemand", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Trace time-step length in minutes (ESOO/EV builders always write 30).",
                    ),
                ),
                (
                    "forecast_year",
                    models.PositiveIntegerField(
                        help_text="Calendar year this Demand's trace is stored against in DemandMatrix"
                    ),
                ),
                (
                    "reference_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The real FacilityScada year whose chronological shape was used as the synthesis prior for this Demand's trace (see esoo_scenario_views.build_scenario_from_esoo). Null if not ESOO-built.",
                        null=True,
                    ),
                ),
                (
                    "esoo_scenario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("expected", "Expected"),
                            ("high", "High"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "poe_level",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(10, "POE10"), (50, "POE50"), (90, "POE90")],
                        null=True,
                    ),
                ),
                (
                    "demand_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("operational", "Operational"),
                            ("underlying", "Underlying"),
                            ("delivered", "Delivered"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("apply_bias_correction", models.BooleanField(default=False)),
                (
                    "csiro_scenario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "charging_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "unmanaged",
                                "Unmanaged (plug-in-on-arrival) — honest baseline, D3",
                            ),
                            ("managed", "Managed (ToU redistribution lever), D3/D11"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "net_of_esoo_ev",
                    models.BooleanField(
                        default=False,
                        help_text="True if the base ESOO trace's own embedded EV estimate was subtracted before adding this EV trace.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set false to hide a superseded/bad build without deleting its trace history.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "esoo_vintage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demands",
                        to="siren_web.esoovintage",
                    ),
                ),
                (
                    "parent_demand",
                    models.ForeignKey(
                        blank=True,
                        help_text="The base ESOO Demand this EV-layered Demand was built from, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ev_derived",
                        to="siren_web.demand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand",
                "verbose_name_plural": "Demands",
                "db_table": "demand",
            },
        ),
        migrations.AddField(
            model_name="esooforecastadjustment",
            name="applied_to_demand",
            field=models.ForeignKey(
                blank=True,
                help_text="Set once this adjustment was actually used to build a Demand forecast",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="esoo_forecast_adjustments",
                to="siren_web.demand",
            ),
        ),
        migrations.AddIndex(
            model_name="demand",
            index=models.Index(
                fields=["forecast_year"], name="demand_forecas_a56b35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demand",
            index=models.Index(fields=["is_active"], name="demand_is_acti_7c8302_idx"),
        ),
    ]
