# Generated by Django 5.2.7 on 2026-09-23 09:47
"""
Data migration: port every 'Load' facility's trace and provenance into the
new Demand/DemandMatrix models introduced by 0195.

This is a one-way carry, not a reversible schema change -- reverse_code is
a no-op that logs a warning rather than pretending to undo it. Run and spot-
check this against a copy of production data (row counts, a few
parent_demand links, a byte-for-byte trace diff) before merging 0197, which
deletes the Load facilities/Technology/SupplyFactorMatrix rows this
migration reads from.

Deliberately uses apps.get_model (historical models) and inlines its own
copy of the DemandMatrix pack/set logic (mirroring
siren_web.services.demand_matrix.set_demand_trace) and its own copy of the
ESOO/EV description-provenance regexes (mirroring
powermatchui.utils.scenario_summary.describe_provenance's old _ESOO_RE/
_EV_RE/_EV_BASE_RE) rather than importing app code that may change shape
independently of this migration.
"""
import re

import numpy as np
from django.db import migrations

_ESOO_RE = re.compile(
    r'WEM ESOO (?P<vintage>\d{4}) \((?P<scenario>\w+), POE(?P<poe>\d+)\) demand forecast for (?P<year>\d{4})'
)
_EV_RE = re.compile(r'CSIRO (?P<scenario>\w+) EV load \((?P<mode>\w+)\) for (?P<year>\d{4})')
_EV_BASE_RE = re.compile(r'Auto-built: (?P<base>.+?) base demand')


def _set_trace(DemandMatrix, year, demand_id, values):
    """Mirrors siren_web.services.demand_matrix.set_demand_trace, inlined
    against the historical DemandMatrix model."""
    values = np.asarray(values, dtype='float32')
    n = values.shape[0]

    try:
        row = DemandMatrix.objects.get(year=year)
        demand_ids = list(row.demand_ids)
        matrix = np.frombuffer(row.data, dtype=row.dtype).reshape(len(demand_ids), row.n_hours).copy()
    except DemandMatrix.DoesNotExist:
        demand_ids = []
        matrix = np.empty((0, n), dtype='float32')

    if n > matrix.shape[1]:
        pad = np.full((matrix.shape[0], n - matrix.shape[1]), np.nan, dtype='float32')
        matrix = np.hstack([matrix, pad]) if matrix.shape[0] else np.empty((0, n), dtype='float32')

    if demand_id in demand_ids:
        i = demand_ids.index(demand_id)
    else:
        demand_ids.append(demand_id)
        matrix = np.vstack([matrix, np.full((1, matrix.shape[1]), np.nan, dtype='float32')])
        i = len(demand_ids) - 1

    matrix[i, :n] = values

    DemandMatrix.objects.update_or_create(
        year=year,
        defaults=dict(demand_ids=demand_ids, n_hours=matrix.shape[1], dtype='float32', data=matrix.tobytes()),
    )


def migrate_load_data_to_demand(apps, schema_editor):
    facilities = apps.get_model('siren_web', 'facilities')
    ScenariosFacilities = apps.get_model('siren_web', 'ScenariosFacilities')
    SupplyFactorMatrix = apps.get_model('siren_web', 'SupplyFactorMatrix')
    Demand = apps.get_model('siren_web', 'Demand')
    DemandMatrix = apps.get_model('siren_web', 'DemandMatrix')
    EsooVintage = apps.get_model('siren_web', 'EsooVintage')
    EsooForecastAdjustment = apps.get_model('siren_web', 'EsooForecastAdjustment')

    load_facilities = list(facilities.objects.filter(idtechnologies__technology_name='Load'))
    if not load_facilities:
        return

    load_facility_ids = [f.idfacilities for f in load_facilities]
    links_by_facility = {}
    for link in ScenariosFacilities.objects.filter(idfacilities__in=load_facility_ids).select_related('idscenarios'):
        links_by_facility.setdefault(link.idfacilities_id, []).append(link.idscenarios)

    matrix_rows = list(SupplyFactorMatrix.objects.order_by('-year'))

    def probe_year_and_trace(facility_id):
        for row in matrix_rows:
            if facility_id in row.facility_ids:
                idx = row.facility_ids.index(facility_id)
                arr = np.frombuffer(row.data, dtype=row.dtype).reshape(len(row.facility_ids), row.n_hours)
                return row.year, arr[idx, :].copy()
        return None, None

    # Pass 1: ESOO-root Demands (description matches _ESOO_RE, or matches
    # neither pattern -- a hand-built/legacy Load facility still gets a
    # bare Demand row rather than being silently dropped).
    demand_by_facility_name = {}
    esoo_facilities, ev_facilities = [], []
    for fac in load_facilities:
        candidates = links_by_facility.get(fac.idfacilities, [])
        owning = next((s for s in candidates if s.title == fac.facility_name), candidates[0] if candidates else None)
        description = (owning.description if owning else '') or ''
        if _EV_RE.search(description):
            ev_facilities.append((fac, candidates, owning, description))
        else:
            esoo_facilities.append((fac, candidates, owning, description))

    for fac, candidates, owning, description in esoo_facilities:
        year, trace = probe_year_and_trace(fac.idfacilities)
        name = fac.facility_name or fac.facility_code or f'facility-{fac.idfacilities}'
        m = _ESOO_RE.search(description)
        defaults = dict(
            description=description,
            interval_minutes=(owning.interval_minutes if owning else 30) or 30,
            forecast_year=year or 0,
            reference_year=owning.reference_year if owning else None,
            is_active=True,
        )
        if m:
            vintage_obj = EsooVintage.objects.filter(year=int(m.group('vintage'))).first()
            defaults.update(
                esoo_vintage=vintage_obj,
                esoo_scenario=m.group('scenario'),
                poe_level=int(m.group('poe')),
                demand_basis='operational',
            )
        demand, _ = Demand.objects.update_or_create(name=name, defaults=defaults)
        demand_by_facility_name[name] = demand

        if year is not None and trace is not None:
            _set_trace(DemandMatrix, year, demand.iddemand, trace)

        if owning is not None:
            EsooForecastAdjustment.objects.filter(applied_to_scenario=owning).update(applied_to_demand=demand)

        for scenario in candidates:
            scenario.weather_year = year
            scenario.save(update_fields=['weather_year'])

    # Pass 2: EV-derived Demands (parent_demand resolved from _EV_BASE_RE's
    # parsed base title against the ESOO-root Demands just created above).
    # A historically chained EV-on-EV build (base itself EV-derived) is a
    # best-effort case: if its own base hasn't been processed yet in this
    # same pass, parent_demand falls back to None rather than resolving --
    # narrow enough (no evidence of this in practice) not to warrant a
    # multi-pass fixpoint here.
    for fac, candidates, owning, description in ev_facilities:
        year, trace = probe_year_and_trace(fac.idfacilities)
        name = fac.facility_name or fac.facility_code or f'facility-{fac.idfacilities}'
        ev_m = _EV_RE.search(description)
        base_m = _EV_BASE_RE.search(description)
        parent = demand_by_facility_name.get(base_m.group('base')) if base_m else None
        defaults = dict(
            description=description,
            interval_minutes=(owning.interval_minutes if owning else 30) or 30,
            forecast_year=year or 0,
            reference_year=owning.reference_year if owning else None,
            is_active=True,
            parent_demand=parent,
            csiro_scenario=ev_m.group('scenario') if ev_m else '',
            charging_mode=ev_m.group('mode') if ev_m else '',
            net_of_esoo_ev="net of ESOO" in description,
        )
        demand, _ = Demand.objects.update_or_create(name=name, defaults=defaults)
        demand_by_facility_name[name] = demand

        if year is not None and trace is not None:
            _set_trace(DemandMatrix, year, demand.iddemand, trace)

        for scenario in candidates:
            scenario.weather_year = year
            scenario.save(update_fields=['weather_year'])


def warn_irreversible(apps, schema_editor):
    import logging
    logging.getLogger(__name__).warning(
        "0196_migrate_load_data_to_demand cannot be auto-reversed; restore Demand/DemandMatrix "
        "and Scenarios.weather_year/EsooForecastAdjustment.applied_to_demand from a backup if needed."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0195_demand_and_demand_matrix"),
    ]

    operations = [
        migrations.RunPython(migrate_load_data_to_demand, reverse_code=warn_irreversible),
    ]
