# Generated by Django 5.2.7 on 2026-09-23 09:52
"""
Drop the Load-facility scaffold now that 0196 has carried every Load
facility's trace and provenance into Demand/DemandMatrix.

Destructive -- gate this on 0196 having been verified against a real copy
of production data first (row counts, parent_demand links, a byte-for-byte
trace diff), same discipline already applied to this project's other
migrate-then-drop cutovers (0181/0187/0189/0191).

Deletes:
  - every `facilities` row with idtechnologies__technology_name='Load'
    (cascades to ScenariosFacilities/ScenariosTechnologies/FacilityStorage/
    FacilitySolar/FacilityWindTurbines/FacilityGridConnections/
    FacilityCELAlignment/etc. -- every idfacilities FK in models.py is
    on_delete=CASCADE, verified before writing this migration)
  - the Technologies(technology_name='Load') singleton itself (defensively
    clears any TechnologyYears/variations rows first, since those FK
    Technologies with on_delete=RESTRICT and would otherwise block it --
    Load never legitimately has either, but this migration doesn't assume
    that)
  - those facilities' rows out of every SupplyFactorMatrix year

Also removes Scenarios.reference_year and
EsooForecastAdjustment.applied_to_scenario, whose values 0196 already
carried across to Demand.reference_year / EsooForecastAdjustment.
applied_to_demand.
"""
import numpy as np
from django.db import migrations


def drop_load_facility_scaffold(apps, schema_editor):
    facilities = apps.get_model('siren_web', 'facilities')
    Technologies = apps.get_model('siren_web', 'Technologies')
    SupplyFactorMatrix = apps.get_model('siren_web', 'SupplyFactorMatrix')
    TechnologyYears = apps.get_model('siren_web', 'TechnologyYears')
    variations = apps.get_model('siren_web', 'variations')

    load_facility_ids = list(facilities.objects.filter(
        idtechnologies__technology_name='Load'
    ).values_list('idfacilities', flat=True))

    if load_facility_ids:
        wanted = set(load_facility_ids)
        for row in SupplyFactorMatrix.objects.all():
            if not (wanted & set(row.facility_ids)):
                continue
            keep = [(i, fid) for i, fid in enumerate(row.facility_ids) if fid not in wanted]
            if not keep:
                row.delete()
                continue
            idxs = [i for i, _ in keep]
            matrix = np.frombuffer(row.data, dtype=row.dtype).reshape(len(row.facility_ids), row.n_hours)
            new_matrix = matrix[idxs, :].copy()
            row.facility_ids = [fid for _, fid in keep]
            row.data = new_matrix.tobytes()
            row.save()

        facilities.objects.filter(idfacilities__in=load_facility_ids).delete()

    load_tech = Technologies.objects.filter(technology_name='Load').first()
    if load_tech is not None:
        TechnologyYears.objects.filter(idtechnologies=load_tech).delete()
        variations.objects.filter(idtechnologies=load_tech).delete()
        load_tech.delete()


def warn_irreversible(apps, schema_editor):
    import logging
    logging.getLogger(__name__).warning(
        "0197_drop_load_facility_scaffold cannot be auto-reversed; restore Load facilities/"
        "Technologies/SupplyFactorMatrix rows from a backup if needed."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0196_migrate_load_data_to_demand"),
    ]

    operations = [
        migrations.RunPython(drop_load_facility_scaffold, reverse_code=warn_irreversible),
        migrations.RemoveField(
            model_name="esooforecastadjustment",
            name="applied_to_scenario",
        ),
        migrations.RemoveField(
            model_name="scenarios",
            name="reference_year",
        ),
    ]
