# Generated by Django 5.2.7 on 2026-09-24 09:35
# Split out of the scenario-taxonomy migration: this Meta-only change
# (verbose_name/verbose_name_plural) was already pending, unrelated to the
# scenario work in 0199.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0197_drop_load_facility_scaffold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gencostcostfigure",
            options={
                "verbose_name": "GenCost Figure",
                "verbose_name_plural": "GenCost Figures",
            },
        ),
    ]
