# Generated by Django 5.2.7 on 2026-09-24 09:35
# Hand-adjusted: makemigrations --no-input can't detect the weather_year ->
# forecast_year rename (it has no TTY to answer the rename prompt) and
# emits a destructive RemoveField+AddField pair instead. Replaced with
# RenameField + AlterField here so existing Scenarios rows keep their data.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0198_gencostcostfigure_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioType",
            fields=[
                ("idscenariotype", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system_default",
                    models.BooleanField(
                        default=False,
                        help_text="True for the built-in types seeded by migration, as opposed to a user-added one.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario Type",
                "verbose_name_plural": "Scenario Types",
                "db_table": "scenariotype",
            },
        ),
        migrations.RenameField(
            model_name="scenarios",
            old_name="weather_year",
            new_name="forecast_year",
        ),
        migrations.AlterField(
            model_name="scenarios",
            name="forecast_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text=(
                    "The year this scenario's facility portfolio represents. For "
                    "manually curated scenarios (e.g. 'Current') this is typically "
                    "left as whatever real year was set when the field was still "
                    "called weather_year; for auto-generated Facilities Take-up "
                    "scenarios this is the future build-out year (e.g. 2035). No "
                    "longer used to pick SupplyFactorMatrix data -- dispatch's "
                    "weather-trace year always comes from the session (see "
                    "siren_web.database_operations.resolve_baseline_year)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="scenarios",
            name="is_auto_generated",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True for scenarios created by generate_facilities_takeup_scenarios; "
                    "safe to regenerate/overwrite membership on rerun. Manual edits to "
                    "such a scenario are not protected from a later regeneration."
                ),
            ),
        ),
        migrations.AddField(
            model_name="scenarios",
            name="probability_band",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("expected", "Expected"), ("high", "High")],
                help_text="Set by generate_facilities_takeup_scenarios; blank for manually curated scenarios.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DemandScenarios",
            fields=[
                ("iddemandscenarios", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "forecast_year",
                    models.PositiveIntegerField(
                        help_text="Mirrors demand.forecast_year; kept explicit for uniform querying alongside the Scenarios model's own forecast_year."
                    ),
                ),
                (
                    "probability_band",
                    models.CharField(
                        blank=True,
                        choices=[("low", "Low"), ("expected", "Expected"), ("high", "High")],
                        help_text="Unifies ESOO's low/expected/high and CSIRO's Low/Medium/High into one vocabulary for the picker UI.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_scenario",
                        to="siren_web.demand",
                    ),
                ),
                (
                    "scenario_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demand_scenarios",
                        to="siren_web.scenariotype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Scenario",
                "verbose_name_plural": "Demand Scenarios",
                "db_table": "demandscenarios",
            },
        ),
        migrations.AddField(
            model_name="scenarios",
            name="scenario_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text="Taxonomy tag, e.g. 'Facilities Take-up' for auto-generated portfolios. Null for manually curated scenarios such as 'Current'.",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facility_scenarios",
                to="siren_web.scenariotype",
            ),
        ),
    ]
