# Generated by Django 5.2.7 on 2026-09-24 09:35
"""
Data migration: seed the three system-default ScenarioType rows and create
a DemandScenarios wrapper for every pre-existing Demand row, so nothing
already built (by esoo_scenario_views.build_scenario_from_esoo /
ev_scenario_views.build_scenario_from_ev before this migration) is left
outside the new taxonomy.

Classification: a Demand row with parent_demand_id is None is "Demand
Forecast" (esoo_scenario -> probability_band directly, since both use
low/expected/high); one with parent_demand_id set is "Load Factor - EV
Charging" (csiro_scenario -> probability_band, mapping medium -> expected
to line up with ESOO's three-band vocabulary).
"""
from django.db import migrations


def seed_and_backfill(apps, schema_editor):
    ScenarioType = apps.get_model('siren_web', 'ScenarioType')
    Demand = apps.get_model('siren_web', 'Demand')
    DemandScenarios = apps.get_model('siren_web', 'DemandScenarios')

    facilities_takeup, _ = ScenarioType.objects.get_or_create(
        name='Facilities Take-up',
        defaults={
            'description': (
                "Commissioned, grid-connected facilities -- a Scenarios row's "
                "facility/technology portfolio, either manually curated or "
                "auto-generated (Low/Expected/High) by "
                "generate_facilities_takeup_scenarios from each facility's "
                "commissioning probability, commissioning date and retirement date."
            ),
            'is_system_default': True,
        },
    )
    demand_forecast, _ = ScenarioType.objects.get_or_create(
        name='Demand Forecast',
        defaults={
            'description': "Overall grid demand, AEMO ESOO-derived (a Demand row with no parent_demand).",
            'is_system_default': True,
        },
    )
    load_factor_ev, _ = ScenarioType.objects.get_or_create(
        name='Load Factor - EV Charging',
        defaults={
            'description': "EV charging load layered onto a base Demand Forecast, AEMO IASR/CSIRO-derived.",
            'is_system_default': True,
        },
    )

    _ESOO_BAND = {'low': 'low', 'expected': 'expected', 'high': 'high'}
    _CSIRO_BAND = {'low': 'low', 'medium': 'expected', 'high': 'high'}

    for demand in Demand.objects.all():
        if DemandScenarios.objects.filter(demand_id=demand.pk).exists():
            continue

        if demand.parent_demand_id is None:
            scenario_type = demand_forecast
            probability_band = _ESOO_BAND.get(demand.esoo_scenario, '')
        else:
            scenario_type = load_factor_ev
            probability_band = _CSIRO_BAND.get(demand.csiro_scenario, '')

        DemandScenarios.objects.create(
            name=demand.name,
            scenario_type=scenario_type,
            demand_id=demand.pk,
            forecast_year=demand.forecast_year,
            probability_band=probability_band,
        )


def noop_reverse(apps, schema_editor):
    """
    Not reversed: deleting the seeded ScenarioType/DemandScenarios rows
    would cascade or orphan anything created against them since this
    migration ran. Reversing the schema (0199) is enough to undo the
    feature; this data is left in place.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0199_scenario_taxonomy"),
    ]

    operations = [
        migrations.RunPython(seed_and_backfill, noop_reverse),
    ]
