# Generated by Django 5.2.7 on 2026-09-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0202_scenarios_probability_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityGenerators",
            fields=[
                (
                    "idfacilitygenerators",
                    models.AutoField(
                        db_column="idfacilitygenerators",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capacity_max",
                    models.FloatField(
                        blank=True,
                        help_text="Fraction (0-1) of this facility's own capacity usable as max output. Falls back to the Technology default when null.",
                        null=True,
                    ),
                ),
                (
                    "capacity_min",
                    models.FloatField(
                        blank=True,
                        help_text="Fraction (0-1) of this facility's own capacity that must run (minimum stable generation). Falls back to the Technology default when null.",
                        null=True,
                    ),
                ),
                ("rampdown_max", models.IntegerField(blank=True, null=True)),
                ("rampup_max", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idfacilities",
                    models.ForeignKey(
                        db_column="idfacilities",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generator_installations",
                        to="siren_web.facilities",
                    ),
                ),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        db_column="idtechnologies",
                        limit_choices_to={"category": "Generator"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generator_facility_installations",
                        to="siren_web.technologies",
                    ),
                ),
            ],
            options={
                "db_table": "FacilityGenerators",
                "unique_together": {("idfacilities", "idtechnologies")},
            },
        ),
    ]
