# Generated by Django 5.2.7 on 2026-09-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siren_web", "0204_backfill_facilitygenerators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenarios",
            name="forecast_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The year this scenario's facility portfolio represents. For manually curated scenarios (e.g. 'Current') this is typically left as whatever real year was set when the field was still called weather_year; for auto-generated Facilities Take-up scenarios this is the future build-out year (e.g. 2035). Not used to pick SupplyFactorMatrix data -- dispatch's supply-trace year always comes from the selected Demand forecast's reference_year (see siren_web.database_operations.resolve_baseline_year / Demand.reference_year).",
                null=True,
            ),
        ),
    ]
