"""
Django settings for siren_web project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import crispy_bootstrap5
import logging
from pathlib import Path
import os, sys
import toml

# Set up logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

# Configure logging for Django
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'formatters': {
        'simple': {
            'format': '%(asctime)s - %(levelname)s - %(message)s'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SECRETS_FILE = os.path.join(BASE_DIR, '.django', 'secrets.toml')

# In development lLoad secrets from the secrets.toml file
if os.path.exists(SECRETS_FILE):
    with open(SECRETS_FILE) as f:
        secrets = toml.load(f)
else:
        # In production load secrets from environment variables
    secrets = {}
    logger = logging.getLogger(__name__)
    try:
        secrets['database'] = {
            'name': os.environ['DB_NAME'],
            'user': os.environ['DB_USER'],
            'password': os.environ['DB_PASSWORD'],
            'host': os.environ['DB_HOST'],
            'port': int(os.environ['DB_PORT'])
        }
        secrets['django'] = {'secret_key': os.environ['DJANGO_SECRET_KEY']}
        secrets['authenticate'] = {
            'member_pass': os.environ['MEMBER_PASS'],
            'lapsed_pass': os.environ['LAPSED_PASS'],
            'subscriber_pass': os.environ['SUBSCRIBER_PASS'],
        }
    except KeyError as e:
        logger.debug(f"Error: Environment variable {e} not set.")
        sys.exit(1)
    except ValueError as e:
        logger.debug(f"Error: Invalid value for environment variable {e}.")
        sys.exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secrets['django']['secret_key']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'siren-web.sen.asn.au']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "siren_web",
    "powermapui",
    "powermatchui",
    "powerplotui",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "siren_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            os.path.join(BASE_DIR, 'powermapui/templates'),
            os.path.join(BASE_DIR, 'powermatchui/templates'),
            os.path.join(BASE_DIR, 'powerplotui/templates'),
            os.path.join(BASE_DIR, 'siren_web/templates'),
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(os.path.dirname(crispy_bootstrap5.__file__), 'templates')
            ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "siren_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': secrets['database']['name'],
        'USER': secrets['database']['user'],
        'PASSWORD': secrets['database']['password'],
        'HOST': secrets['database']['host'],
        'PORT': secrets['database']['port'],
        'sql_mode': 'STRICT_TRANS_TABLES',
    }
}
USER_PASS = {
    'member_pass': secrets['authenticate']['member_pass'],
    'lapsed_pass': secrets['authenticate']['lapsed_pass'],
    'subscriber_pass': secrets['authenticate']['subscriber_pass'],
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/accounts/logout/'



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/siren_web/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
STATIC_ROOT = BASE_DIR / 'static_collected'
# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_RENDERER_CLASS = "crispy_bootstrap5.renderers.AccordionJsRenderer"
# Powermap settings
WEATHER_DATA_DIR = BASE_DIR / 'siren_web' / 'siren_files' / 'SWIS' / 'siren_data' / 'weather_files'
POWER_CURVES_DIR = BASE_DIR = BASE_DIR / 'siren_web' / 'siren_files' / 'siren_data' / 'plant_data'