# Generated by Django 5.0.1 on 2024-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.CharField(max_length=20)),
                ("parameter", models.CharField(max_length=45)),
                ("value", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "Settings",
            },
        ),
    ]
