# Generated by Django 5.0.1 on 2024-02-29 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powermatchui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="sirensystem",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "sirensystem",
            },
        ),
        migrations.RemoveField(
            model_name="generatorattributes",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="generatorattributes",
            name="emissions",
        ),
        migrations.RemoveField(
            model_name="generatorattributes",
            name="mult",
        ),
        migrations.RemoveField(
            model_name="scenarios",
            name="year",
        ),
        migrations.RemoveField(
            model_name="zones",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="zones",
            name="constraintid",
        ),
        migrations.RemoveField(
            model_name="zones",
            name="existing",
        ),
        migrations.RemoveField(
            model_name="zones",
            name="idscenarios",
        ),
        migrations.AddField(
            model_name="demand",
            name="idscenarios",
            field=models.ForeignKey(
                db_column="idScenarios",
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="powermatchui.scenarios",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="demand",
            name="idtechnologies",
            field=models.ForeignKey(
                db_column="idTechnologies",
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="powermatchui.technologies",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technologies",
            name="capacity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="technologies",
            name="emissions",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="technologies",
            name="mult",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="technologies",
            name="year",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="zones",
            name="description",
            field=models.CharField(
                blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="zones",
            name="name",
            field=models.CharField(
                blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=45, null=True
            ),
        ),
        migrations.CreateModel(
            name="facilities",
            fields=[
                (
                    "idfacilities",
                    models.PositiveIntegerField(
                        db_column="idfacilities", primary_key=True, serialize=False
                    ),
                ),
                (
                    "facility_name",
                    models.CharField(
                        blank=True, db_column="facility_name", max_length=45, null=True
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        db_column="capacity",
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "capacityfactor",
                    models.DecimalField(
                        blank=True,
                        db_column="capacityfactor",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "generation",
                    models.DecimalField(
                        blank=True,
                        db_column="generation",
                        decimal_places=0,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "transmitted",
                    models.DecimalField(
                        blank=True,
                        db_column="transmitted",
                        decimal_places=0,
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        db_column="idtechnologies",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="powermatchui.technologies",
                    ),
                ),
                (
                    "idzones",
                    models.ForeignKey(
                        blank=True,
                        db_column="idzones",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="powermatchui.zones",
                    ),
                ),
            ],
            options={
                "db_table": "facilities",
            },
        ),
        migrations.CreateModel(
            name="supplyfactors",
            fields=[
                (
                    "idsupplyfactors",
                    models.AutoField(
                        db_column="idsupplyfactors", primary_key=True, serialize=False
                    ),
                ),
                ("hour", models.IntegerField(blank=True, null=True)),
                ("supply", models.IntegerField(blank=True, null=True)),
                (
                    "quantum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "idscenarios",
                    models.ForeignKey(
                        blank=True,
                        db_column="idscenarios",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="powermatchui.scenarios",
                    ),
                ),
                (
                    "idtechnologies",
                    models.ForeignKey(
                        blank=True,
                        db_column="idtechnologies",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="powermatchui.technologies",
                    ),
                ),
                (
                    "idzones",
                    models.ForeignKey(
                        blank=True,
                        db_column="idzones",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="powermatchui.zones",
                    ),
                ),
            ],
            options={
                "db_table": "supplyfactors",
            },
        ),
    ]
