# Generated by Django 5.0.1 on 2024-02-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powermatchui", "0001_initial"),
    ]

    operations = [
    ]
