# Generated by Django 5.0.1 on 2024-03-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("powermatchui", "0008_alter_technologies_capacity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="demand",
            unique_together={("iddemand", "idtechnologies", "hour")},
        ),
        migrations.RemoveField(
            model_name="generators",
            name="constr",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="constraintid",
        ),
    ]
