# Generated by Django 5.0.1 on 2024-03-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("powermatchui", "0012_analysis_component_alter_analysis_heading"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Generators",
        ),
    ]
