# Generated by Django 5.0.1 on 2024-03-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("powermatchui", "0013_delete_generators"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stations",
        ),
    ]
