# Generated by Django 5.0.1 on 2024-03-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powermatchui", "0015_variations_capacities"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenariosFacilities",
            fields=[
                (
                    "idscenariosfacilities",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "idfacilities",
                    models.ForeignKey(
                        db_column="idfacilities",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="powermatchui.facilities",
                    ),
                ),
                (
                    "idscenarios",
                    models.ForeignKey(
                        db_column="idScenarios",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="powermatchui.scenarios",
                    ),
                ),
            ],
            options={
                "db_table": "ScenariosFacilities",
            },
        ),
        migrations.DeleteModel(
            name="capacities",
        ),
    ]
