# Generated by Django 5.0.1 on 2024-03-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powermatchui", "0016_scenariosfacilities_delete_capacities"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariosfacilities",
            name="merit_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
